var i;
i=global.servers_in_list;
global.server_listed_ip[i]=argument0;
global.server_listed_port_udp[i]=argument1;
global.server_listed_port_udp[i]=argument2;
global.server_listed_x[i]=argument3;
global.server_listed_y[i]=argument4;
global.server_listed_last[i]=argument5;
global.servers_in_list+=1;
return i;
