// Chemical ids and their names
global.ElementGroupName[0]="Non-metallic";
global.ElementGroupName[1]="Metal";
global.ElementGroupName[2]="Alkali";
global.ElementGroupName[3]="Alkaline Metal";
global.ElementGroupName[4]="Metalloid";
global.ElementGroupName[5]="Noble Gas";
global.ElementGroupName[6]="Transition Metal";
global.ElementGroupName[7]="Halogen";
global.ElementGroupName[8]="Actinide";
global.ElementGroupName[9]="Lanthanide";

table("Elements","Symbol","Name","Group","Rarity","Freezing","Boiling","Density");
row("Elements","H",  "Hydrogen",      0,  0.9,    273-259.34,    273-252.87,    0.01       );
row("Elements","He", "Helium",        0,  0.5,    273-272.24,    273-268.93,    0.02       );
row("Elements","Li", "Lithium",       2,  0.2,    273+180.5,     273+1342,      0.08       );
row("Elements","Be", "Beryllium",     3,  0.19,   273-259.34,    273-252.87,    0.09       );
row("Elements","B",  "Boron",         4,  0.19,   273-259.34,    273-252.87,    0.010      ); 
row("Elements","C",  "Carbon",        0,  0.3,    273+3550,      273+3800,      0.01       ); 
row("Elements","N",  "Nitrogen",      0,  0.1,    273-210.0,     273-195.79,    0.01       ); 
row("Elements","O",  "Oxygen",        0,  0.1,    273-218.79,    273-182.95,    0.01       ); 
row("Elements","F",  "Flourine",      7,  0.1,    273-219.67,    273-118.12,    0.01       ); 
row("Elements","Ne", "Neon",          5,  0.9,    273-258.59,    273-246.08,    0.01       );
row("Elements","Si", "Silicon",       0,  0.1,    273-219.67,    273-118.12,    0.01       ); 
row("Elements","Na", "Sodium",        2,  0.9,    273+97.8,      273+883,       0.5        ); 
row("Elements","Mg", "Magnesium",     3,  0.1,    273+650,       273+1090,      0.4        ); 
row("Elements","Al", "Aluminum",      1,  0.1,    273+660.32,    273+2519,      0.5        ); 
row("Elements","Si", "Silicon",       4,  0.3,    273+1414,      273+3265,      0.01       ); 
row("Elements","P",  "Phosphorous",   0,  0.3,    273+44.15,     273+280.5,     0.5        ); 
row("Elements","S",  "Sulfur",        0,  0.3,    273+119.6,     273+444.60,    0.5        ); 
row("Elements","Cl", "Chlorine",      7,  0.3,    273-101.5,     273-34.4,      0.01       ); 
row("Elements","Ar", "Argon",         5,  0.3,    273-189.35,    273-185.85,    0.01       ); 
row("Elements","K",  "Potassium",     2,  0.3,    273+63.5,      273+759,       0.5       ); 
row("Elements","Ca", "Calcium",       3,  0.2,    273+842,       273+1484,      0.4        ); 
row("Elements","Sc", "Scandium",      6,  0.02,   273+1541,      273+2836,      0.44       ); 
row("Elements","Ti", "Titanium",      6,  0.1,    273+1414,      273+3265,      0.479      ); 
row("Elements","V",  "Vanadium",      6,  0.03,   273+1910,      273+3407,      0.509      ); 
row("Elements","Cr", "Chromium",      6,  0.12,   273+1907,      273+2671,      0.51996    ); 
row("Elements","Mn", "Manganese",     6,  0.3,    273+1246,      273+2061,      0.54938    ); 
row("Elements","Fe", "Iron",          6,  0.3,    273+1538,      273+2861,      0.55847    ); 
row("Elements","Co", "Cobalt",        6,  0.3,    273+1495,      273+2927,      0.589332   ); 
row("Elements","Ni", "Nickel",        6,  0.3,    273+1455,      273+2913,      0.5870     );
row("Elements","Cu", "Copper",        6,  0.3,    273+1084.6,    273+2562,      0.55847    ); 
row("Elements","Zn", "Zinc",          6,  0.3,    273+419.5,     273+907,       0.6538     ); 
row("Elements","Ga", "Gallium",       1,  0.3,    273+29.76,     273+2204,      0.69       ); 
row("Elements","Ge", "Germanium",     4,  0.3,    273+1414,      273+3265,      0.7259     ); 
row("Elements","As", "Arsenic",       4,  0.3,    273+817,       273+603,       0.749216   ); 
row("Elements","Se", "Selenium",      0,  0.3,    273+220.5,     273+685,       0.7896     ); 
row("Elements","Br", "Bromine",       7,  0.3,    273+1414,      273+3265,      0.79904    ); 
row("Elements","Kr", "Krypton",       5,  0.02,   273-157.38,    273+153.22,    0.8380     ); 
row("Elements","Rb", "Rubidium",      2,  0.08,   273+39.3,      273+688,       0.854678   ); 
row("Elements","Sr", "Strontium",     3,  0.3,    273+777,       273+1382,      0.8762    ); 
row("Elements","Y",  "Yttrium",       6,  0.3,    273+1522,      273+3345,      0.889059   ); 
row("Elements","Zr", "Zirconium",     6,  0.13,   273+1855,      273+4409,      0.7259     ); 
row("Elements","Nb", "Niobium",       6,  0.12,   273+2477,      273+4744,      0.929064   ); 
row("Elements","Mo", "Molybdenum",    6,  0.11,   273+2623,      273+4639,      0.9594     ); 
row("Elements","Tc", "Technetium",    6,  0.13,   273+2157,      273+4265,      0.97       ); 
row("Elements","Ru", "Ruthenium",     6,  0.13,   273+2334,      273+4150,      1.0107     ); 
row("Elements","Rh", "Rhodium",       6,  0.13,   273+1964,      273+3695,      1.029055   ); 
row("Elements","Pd", "Palladium",     6,  0.13,   273+1554.9,    273+2963,      1.064      ); 
row("Elements","Ag", "Silver",        6,  0.13,   273+961.78,    273+2162,      1.07868    ); 
row("Elements","Cd", "Cadmium",       6,  0.13,   273+321.07,    273+767,       1.124      ); 
row("Elements","In", "Indium",        1,  0.13,   273+156.6,     273+2072,      1.1482     ); 
row("Elements","Sn", "Tin",           1,  0.13,   273+231.93,    273+2602,      1.1869     ); 
row("Elements","Sb", "Antimony",      1,  0.01,   273+630.63,    273+1587,      1.2175     ); 
row("Elements","Te", "Tellurium",     0,  0.13,   273+449.5,     273+988,       1.2760     ); 
row("Elements","I",  "Iodine",        7,  0.13,   273+113.7,     273+184.4,     1.269045   ); 
row("Elements","Xe", "Xenon",         5,  0.13,   273+321.07,    273+767,       1.124      ); 
row("Elements","Cs", "Cesium",        2,  0.13,   273+28.5,      273+671,       1.329054   ); 
row("Elements","Ba", "Barium",        3,  0.13,   273+727,       273+1897,      1.34       ); 
row("Elements","La", "Lanthanum",     6,  0.13,   273+918,       273+1897,      1.389055   ); 
row("Elements","Ce", "Cerium",        9,  0.13,   273+798,       273+3443,      1.389055   ); 
row("Elements","Pr", "Praseodymium",  9,  0.13,   273+931,       273+3520,      1.389055   ); 
row("Elements","Nd", "Neodymium",     9,  0.13,   273+1021,      273+3074,      1.4424     ); 
row("Elements","Pm", "Promethium",    9,  0.03,   273+1042,      273+3000,      1.45       ); 
row("Elements","Sm", "Samarium",      9,  0.03,   273+1074,      273+1794,      1.45       ); 
row("Elements","Eu", "Europium",      9,  0.03,   273+822,       273+1529,      1.5196     ); 
row("Elements","Gd", "Gadolinium",    9,  0.03,   273+1313,      273+3273,      1.5725     ); 
row("Elements","Tb", "Terbium",       9,  0.03,   273+1356,      273+3230,      1.589254   ); 
row("Elements","Dy", "Dysprosium",    9,  0.13,   273+1413,      273+2567,      1.625      ); 
row("Elements","Ho", "Holmium",       9,  0.13,   273+1474,      273+2700,      1.649304   ); 
row("Elements","Er", "Erbium",        9,  0.01,   273+1529,      273+2868,      1.6726     ); 
row("Elements","Tm", "Thulium",       9,  0.13,   273+1545,      273+1950,      1.689342   ); 
row("Elements","Yb", "Ytterbium",     9,  0.13,   273+819,       273+1196,      1.7304     ); 
row("Elements","Lu", "Lutetium",      9,  0.13,   273+1663,      273+3402,      1.7497     ); 
row("Elements","Hf", "Hafnium",       6,  0.13,   273+2233,      273+4603,      1.7849     ); 
row("Elements","Ta", "Tantalum",      6,  0.13,   273+3017,      273+5458,      1.809479   ); 
row("Elements","W", "Tungsten",       6,  0.13,   273+3422,      273+5555,      1.835      ); 
row("Elements","Re", "Rhenium",       6,  0.13,   273+3186,      273+5596,      1.86207    ); 
row("Elements","Os", "Osmium",        6,  0.13,   273+3033,      273+5012,      1.902      ); 
row("Elements","Ir", "Iridium",       6,  0.13,   273+2446,      273+4428,      1.9222     ); 
row("Elements","Pt", "Platinum",      6,  0.02,   273+1768.4,    273+3825,      1.9509     ); 
row("Elements","Au", "Gold",          6,  0.03,   273+1064.18,   273+2856,      1.969665   ); 
row("Elements","Hg", "Mercury",       6,  0.13,   273-38.83,     273+356.73,    2.0059     ); 
row("Elements","Tl", "Thallium",      1,  0.13,   273+304,       273+1473,      2.0437     ); 
row("Elements","Pb", "Lead",          1,  0.13,   273+327.46,    273+1749,      2.072      ); 
row("Elements","Bi", "Bismuth",       1,  0.13,   273+271.4,     273+1564,      2.089804   ); 
row("Elements","Po", "Polonium",      1,  0.04,   273+254,       273+962,       2.09       ); 
row("Elements","At", "Astatine",      7,  0.04,   273+254,       273+962,       2.10       ); 
row("Elements","Rn", "Radon",         5,  0.01,   273-71,        273-61.7,      2.22       ); 
row("Elements","Fr", "Francium",      2,  0.001,  273+27,        273+677,       2.23       ); 
row("Elements","Ra", "Radium",        3,  0.001,  273+700,       273+1140,      2.260254   ); 
row("Elements","Ac", "Actinium",      6,  0.001,  273+700,       273+1140,      2.27       ); 
row("Elements","Th", "Thorium",       8,  0.001,  273+1750,      273+4788,      2.32       ); 
row("Elements","Pa", "Protactinium",  8,  0.001,  273+1572,      273+4000,      2.37       ); 
row("Elements","U",  "Uranium",       8,  0.001,  273+1135,      273+4131,      2.38       ); 
row("Elements","Np", "Neptunium",     8,  0.001,  273+644,       273+3900,      2.370482   ); 
row("Elements","Pu", "Plutonium",     8,  0.001,  273+640,       273+3228,      2.44       ); 
row("Elements","Am", "Americium",     8,  0.001,  273+1176,      273+2011,      2.43       ); 
row("Elements","Cm", "Curium",        8,  0.001,  273+1345,      273+3100,      2.47       ); 
row("Elements","Bk", "Berkelium",     8,  0.001,  273+1050,      273+4200,      2.47       ); 
row("Elements","Cf", "Californium",   8,  0.001,  273+860,       273+3660,      2.51       ); 
row("Elements","Es", "Einsteinium",   8,  0.001,  273+860,       273+3900,      2.52       ); 
row("Elements","Fm", "Fermium",       8,  0.001,  273+1527,      273+7000,      2.57       ); 
row("Elements","Md", "Mendelevium",   8,  0.0001, 273+827,       273+6000,      2.58       ); 
row("Elements","No", "Nobelium",      8,  0.0001, 273+827,       273+6000,      2.59       ); 
row("Elements","Lr", "Lawrencium",    8,  0.0001, 273+1627,      273+10000,     2.62       ); 
row("Elements","Rf", "Rutherfordium", 6,  0.0001, 273+10000,     273+20000,     2.61       ); 
row("Elements","Db", "Dubnium",       6,  0.0001, 273+60000,     273+60000,     2.62       ); 
row("Elements","Sg", "Seaborgium",    6,  0.0001, 273+60000,     273+60000,     2.63       ); 
row("Elements","Bh", "Bohrium",       6,  0.0001, 273+60000,     273+60000,     2.64       ); 
row("Elements","Hs", "Hassium",       6,  0.0001, 273+60000,     273+60000,     2.65       ); 
row("Elements","Mt", "Meitnerium",    6,  0.0001, 273+60000,     273+60000,     2.65       ); 
row("Elements","Ds", "Darmstadtium",  6,  0.0001, 273+60000,     273+60000,     2.67       ); 
row("Elements","Uun","Ununnilium",    6,  0.0001, 273+60000,     273+60000,     2.72       ); 
row("Elements","Uuu","Unununium",     1,  0.0001, 273+60000,     273+60000,     2.72       ); 
row("Elements","Uub","Ununbium",      1,  0.0001, 273+60000,     273+60000,     2.72       ); 
row("Elements","Uuq","Ununquadium",   1,  0.0001, 273+60000,     273+60000,     2.72       );

global.CompoundGroupName[0]="Inorganic";
global.CompoundGroupName[1]="Organic";
global.CompoundGroupName[2]="Biomolecule";
global.CompoundGroupName[3]="Alloy";
global.CompoundGroupName[4]="Mineral";
global.CompoundGroupName[5]="Alchemical";
global.CompoundGroupName[6]="Polyatomic Ion";
global.CompoundGroupName[7]="Anion";
global.CompoundGroupName[8]="Halide";
global.CompoundGroupName[9]="Organohalide";

table("Compounds", "Group", "Name", "E1", "A1", "E2", "A2", "E3", "A3", "E4", "A4", "E5", "A5", "E6", "A6");
row("Compounds",4,"Quartz","Si",1,"O",2);
row("Compounds",4,"Opal","Si",1,"O",4,"H",4);
row("Compounds",4,"Microcline","K",1,"Al",1,"Si",3,"O",8);
row("Compounds",4,"Orthoclase","K",1,"Al",1,"Si",3,"O",8);
row("Compounds",4,"Sanidine","K",1,"Al",1,"Si",3,"O",8);
row("Compounds",4,"Plagioclase Albite","Na",1,"Al",1,"Si",3,"O",8);
row("Compounds",4,"Anorthite","Ca",1,"Al",2,"Si",2,"O",8);
row("Compounds",4,"Nepheline","Na",3,"K",1,"Al",4,"Si",4,"O",16);
row("Compounds",4,"Sodalite","Na",8,"Al",6,"Si",6,"O",24,"C",12);
row("Compounds",4,"Stilbite","Na",2,"Ca",4,"Al",10,"Si",26,"O",72);
row("Compounds",4,"Serpentine","Mg",3,"Si",2,"O",5);
row("Compounds",4,"Kaolinite","Al",2,"Si",2,"O",5);
row("Compounds",4,"Talc","Mg",3,"Si",4,"O",10);
row("Compounds",4,"Muscovite","K",1,"Al",2,"Si",3);
row("Compounds",4,"Biotite","K",1,"Mg",3,"Fe",3,"Al",1,"Si",3);
row("Compounds",4,"Chlorite","Mg",6,"Fe",6,"Si",4,"O",10);
row("Compounds",4,"Beryl","Al",2,"Be",3,"Si",6,"O",18);
row("Compounds",4,"Tourmaline","Na",1,"Mg",3,"Fe",3,"Li",3,"Al",3);
row("Compounds",4,"Actinolite","Ca",2,"Fe",5,"Mg",5,"Si",8,"O",22);
row("Compounds",4,"Glaucophane","Na","Mg",6,"Al",2,"Si",8,"O",22);
row("Compounds",4,"Enstatite","Mg",2,"Si",2,"O",6);
row("Compounds",4,"Diopside","Ca",1,"Mg",1,"Si",2,"O",6);
row("Compounds",4,"Augite","Ca",1,"Mg",1,"Fe",5,"Si",2,"Al",2,"O",6);
row("Compounds",4,"Wollastonite","Ca",2,"Si",2,"O",6);
row("Compounds",4,"Epidote","Ca",2,"Al",2,"Fe",3,"Si",2,"O",14);
row("Compounds",4,"Staurolite","Fe",2,"Al",9,"O",12,"Si",5);
row("Compounds",4,"Chloritoid","Fe",4,"Mg",2,"Mn",2,"Si",4,"O",4);
row("Compounds",4,"Olivine","Mg",2,"Fe",2,"Si",1,"O",4);
row("Compounds",4,"Garnet", "Ca", 3, "Fe", 3, "Mg", 3, "Mn", 3, "Al", 2, "Si", 3);
row("Compounds",4,"Andalusite","Al",2,"Si",1,"O",5);
row("Compounds",4,"Sillimanite","Al",2,"Si",1,"O",5);
row("Compounds",4,"Kyanite","Al",2,"Si",1,"O",5);
row("Compounds",4,"Aragonite","Ca",2,"C",2,"O",6);
row("Compounds",4,"Dolomite","Ca",1,"Mg",1,"C",2,"O",6);
row("Compounds",4,"Calcite","Ca",2,"C",2,"O",6);
row("Compounds",4,"Malachite","Cu",2,"C",1,"O",5,"H",2);
row("Compounds",4,"Azurite","Cu",3,"C",1,"O",5,"H",2);
row("Compounds",4,"Apatite","Ca",5,"P",1,"O",12,"H",3,"F",3,"Cl",3);
row("Compounds",4,"Magnetite","Fe",3,"O",4);
row("Compounds",4,"Chromite","Fe",1,"Cr",2,"O",4);
row("Compounds",4,"Corundum","Al",2,"O",3);
row("Compounds",4,"Hematite","Fe",2,"O",3);
row("Compounds",4,"Ilmenite","Fe",1,"Ti",1,"O",3);
row("Compounds",4,"Gypsum","Ca",1,"S",1,"O",4,"H",4,"O",4);
row("Compounds",4,"Halite","Na",1,"Cl",1);
row("Compounds",4,"Fluorite","Ca",1,"F",2);
row("Compounds",4,"Stibnite","Sb",2,"S",3);
row("Compounds",4,"Pyrite","Fe",1,"S",2);
row("Compounds",4,"Bornite","Cu",5,"Fe","S",4);
row("Compounds",4,"Galena","Pb",1,"S",1);
row("Compounds",4,"Sphalerite","Zn",1,"S",1);
row("Compounds",4,"Chalcopyrite","Cu",1,"Fe",1,"S",2);
row("Compounds",4,"Molybdenite","Mo",1,"S",2);
row("Compounds",4,"Pyrrhotite","Fe",1,"S",1);
row("Compounds",4,"Arsenopyrite","Fe",1,"As",1,"S",1);
row("Compounds",4,"Cinnabar","Hg",1,"S",1);
row("Compounds",4,"Graphite","C",1);
row("Compounds",4,"Copper","Cu",1);
row("Compounds",4,"Sulfur","S",1);
row("Compounds",9,"Bromomethane","C",1,"H",3,"Br",1);
row("Compounds",9,"Vinylidene chloride","C",2,"H",2,"Cl",1,"I",2);
row("Compounds",9,"Suxamethonium chloride","C",14,"H",30,"N",2,"O",4);
row("Compounds",9,"Oxalyl Chloride","C",2,"O",2,"Cl",2);
row("Compounds",9,"Ipratropium bromide","C",20,"H",30,"N",1,"O",3);
row("Compounds",9,"Iodoform","C",1,"H",1,"I",3);
row("Compounds",9,"Ethyl chloride","C",2,"H",5,"Cl",1);
row("Compounds",9,"Ethidium bromide","C",21,"H",20,"Br",1,"N",3);
row("Compounds",9,"Diethyl aluminium chloride","C",4,"H",10,"Al",1,"Cl",1);
row("Compounds",9,"Dibucaine hydrochloride","C",20,"H",29,"N",3,"O",2);
row("Compounds",9,"Cyanuric chloride","C",3,"Cl",3,"N",3);
row("Compounds",9,"Cyanogen chloride","C",1,"N",1,"Cl",1);
row("Compounds",9,"Chloracetyl chloride","C",2,"H",2,"Cl",2);
row("Compounds",9,"Benzoyl chloride","C",7,"H",5,"Cl",1);
row("Compounds",9,"Benzethonium chloride","C",27,"H",42,"Cl",1,"N",1,"O",2);
row("Compounds",9,"Benzalkonium chloride","C",22,"H",40,"Cl",1);
row("Compounds",9,"Anisoyl chloride","C",8,"H",7,"Cl",1,"O",2);
row("Compounds",9,"Aniline hydrochloride","C",6,"H",8,"Cl",1);
row("Compounds",9,"Allyl chloride","C",3,"H",5,"Cl",1);
row("Compounds",9,"Adipoyl dichloride","C",6,"H",8,"Cl",1,"O",2);
row("Compounds",9,"Acryloyl chloride","C",3,"H",3,"Cl",1,"O",1);
row("Compounds",1,"Zingiberene","C",15,"H",24);
row("Compounds",1,"Yohimbine hydrochloride","C",21,"H",26,"N",2,"O",3);
row("Compounds",1,"Xylose","C",5,"H",10,"O",5);
row("Compounds",1,"Xylenol orange","C",31,"H",28,"N",2,"Na",4,"O",13);
row("Compounds",1,"Xylene","C",8,"H",10);
row("Compounds",1,"Xylene cyanol","C",25,"H",27,"N",2,"Na",1,"O",6,"S",2);
row("Compounds",1,"Xanthone","C",13,"H",8,"O",2);
row("Compounds",1,"Warfarin","C",19,"H",16,"O",4);
row("Compounds",1,"Vitamin S","C",7,"H",6,"O",3);
row("Compounds",1,"Vitamin M","C",19,"H",19,"N",7,"O",6);
row("Compounds",1,"Vitamin H","C",10,"H",16,"N",2,"O",3);
row("Compounds",1,"Vitamin C","C",6,"H",8,"O",6);
row("Compounds",1,"Vitamin B5","C",9,"H",17,"N",1,"O",5);
row("Compounds",1,"Vitamin B4","C",5,"H",5,"N",5);
row("Compounds",1,"Vitamin B3","C",6,"H",5,"N",1,"O",2);
row("Compounds",1,"Vitamin B2","C",17,"H",20,"N",4,"O",6);
row("Compounds",1,"Vitamin B12","C",63,"H",88,"Co",1,"N",14,"O",14);
row("Compounds",1,"Vitamin B1","C",12,"H",17,"N",4,"OS",1,"H",1,"Cl",1);
row("Compounds",1,"Vinyl fluoride","C",2,"H",3);
row("Compounds",1,"Vinyl acetate","C",4,"H",6,"O",2);
row("Compounds",1,"Venlafaxine","C",17,"H",27,"N",1,"O",2);
row("Compounds",1,"Vanillin","C",8,"H",8,"O",3);
row("Compounds",1,"Valproic acid","C",8,"H",16,"O",2);
row("Compounds",1,"Valium","C",16,"H",13,"Cl",1,"N",2);
row("Compounds",1,"Valine","C",5,"H",11,"N",1,"O",2);
row("Compounds",1,"Usnic acid","C",18,"H",16,"O",7);
row("Compounds",1,"Uridine","C",9,"H",12,"N",2,"O",6);
row("Compounds",1,"Uric acid","C",5,"H",4,"N",4,"O",3);
row("Compounds",1,"Urea","C",1,"H",4,"N",2);
row("Compounds",1,"Uracil","C",4,"H",4,"N",2,"O",2);
row("Compounds",1,"Undecanol","C",11,"H",24);
row("Compounds",1,"Umbelliferone","C",9,"H",6,"O",3);
row("Compounds",1,"Tryptophan","C",11,"H",12,"N",2,"O",2);
row("Compounds",1,"Trypan blue","C",34,"H",28,"N",6,"O",14,"S",4);
row("Compounds",1,"Tropinone","C",8,"H",13,"N",1,"O",1);
row("Compounds",1,"Tropane","C",8,"H",15);
row("Compounds",1,"Tris","C",4,"H",11,"N",1,"O",3);
row("Compounds",1,"Triphenylphosphine","C",18,"H",15);
row("Compounds",1,"Triphenylmethanol","C",19,"H",16);
row("Compounds",1,"Triphenylmethane","C",19,"H",16);
row("Compounds",1,"Triphenylene","C",18,"H",12);
row("Compounds",1,"Triphenylantimony","C",18,"H",15,"Sb",1);
row("Compounds",1,"Triphenylamine","C",18,"H",15);
row("Compounds",1,"Triphenyl phosphate","C",18,"H",15,"O",4);
row("Compounds",1,"Trinitrotoluene (TNT)","C",7,"H",5,"N",3,"O",6);
row("Compounds",1,"Trimethylamine","C",3,"H",9);
row("Compounds",1,"Trimethyl phosphite","C",3,"H",9,"O",3);
row("Compounds",1,"Trimethoxyamphetamine","C",12,"H",19,"N",1,"O",3);
row("Compounds",1,"Trifluoromethane","C",1,"H",1,"F",3);
row("Compounds",1,"Trifluoroacetic acid (TFA)","C",2,"H",1,"F",3,"O",2);
row("Compounds",1,"Triethylenediamine","C",6,"H",12,"N",2);
row("Compounds",1,"Triethylene glycol","C",6,"H",14,"O",4);
row("Compounds",1,"Triethylamine","C",6,"H",15);
row("Compounds",1,"Triethylamine hydrochloride","C",6,"H",16,"Cl",1);
row("Compounds",1,"Triethylaluminium","C",6,"H",15,"Al",1);
row("Compounds",1,"Tridecane","C",13,"H",28);
row("Compounds",1,"Triclosan","C",12,"H",7,"Cl",3,"O",2);
row("Compounds",1,"Triclabendazole","C",14,"H",9,"Cl",1,"S",3,"N",2,"O",1);
row("Compounds",1,"Tricine","C",6,"H",13,"N",1,"O",5);
row("Compounds",1,"Trichlorofluoromethane","C",1,"Cl",1,"F",3);
row("Compounds",1,"Trichloroethylene","C",2,"H",1,"Cl",1,"O",3);
row("Compounds",1,"Trichloroacetic acid","C",2,"H",1,"Cl",3,"O",2);
row("Compounds",1,"Tributylphosphine","C",12,"H",27);
row("Compounds",1,"Tributyl phosphate","C",12,"H",27,"O",4);
row("Compounds",1,"Triazole","C",2,"H",3,"N",3);
row("Compounds",1,"Tri-o-cresyl phosphate","C",21,"H",21,"O",4);
row("Compounds",1,"Toluene","C",7,"H",8);
row("Compounds",1,"Toluene diisocyanate","C",9,"H",6,"N",2,"O",2);
row("Compounds",1,"Tocopherol (Vitamin E)","C",29,"H",50,"O",2);
row("Compounds",1,"Tinidazole","C",8,"H",13,"N",3,"O",4);
row("Compounds",1,"Tiglic acid","C",5,"H",8,"O",2);
row("Compounds",1,"Thyroxine (T4)","C",15,"H",11,"I",4,"N",1,"O",4);
row("Compounds",1,"Thymolphthalein","C",28,"H",30,"O",4);
row("Compounds",1,"Thymol","C",10,"H",14);
row("Compounds",1,"Thymine","C",5,"H",6,"N",2,"O",2);
row("Compounds",1,"Thymidine","C",10,"H",14,"N",2,"O",5);
row("Compounds",1,"Threonine","C",4,"H",9,"N",1,"O",3);
row("Compounds",1,"Thorin","C",16,"H",11,"As",1,"N",2,"O",10,"S",2);
row("Compounds",1,"Thiram","C",6,"H",12,"N",2,"S",4);
row("Compounds",1,"Thiourea","C",1,"H",4,"N",2);
row("Compounds",1,"Thiophosgene","C",1,"Cl",2);
row("Compounds",1,"Thiophene","C",4,"H",4);
row("Compounds",1,"Thiazole","C",3,"H",3,"NS",1);
row("Compounds",1,"Thalidomide","C",13,"H",10,"N",2,"O",4);
row("Compounds",1,"Tetryl","C",7,"H",5,"N",5,"O",8);
row("Compounds",1,"Tetrodotoxin","C",11,"H",17,"N",3,"O",8);
row("Compounds",1,"Tetrazine","C",2,"H",2,"N",4);
row("Compounds",1,"Tetrathiafulvalene (TTF)","C",6,"H",4,"S",4);
row("Compounds",1,"Tetranitromethane","C",1,"N",4,"O",8);
row("Compounds",1,"Tetramethylsilane","C",4,"H",12,"Si",1);
row("Compounds",1,"Tetramethrin","C",19,"H",25,"N",1,"O",4);
row("Compounds",1,"Tetrahydronaphthalene","C",10,"H",12);
row("Compounds",1,"Tetrahydrofuran (THF)","C",4,"H",8);
row("Compounds",1,"Tetrahydrocannabinol (d9-THC)","C",21,"H",30,"O",2);
row("Compounds",1,"Tetrahedrane","C",4,"H",4);
row("Compounds",1,"Tetrafluoroethene","C",2,"F",4);
row("Compounds",1,"Tetraethylene glycol","C",4,"H",10,"O",3);
row("Compounds",1,"Carbon tetrachloride","C",1,"Cl",4);
row("Compounds",1,"Tetrachloroethylene","C",2,"Cl",4);
row("Compounds",1,"Testosterone","C",19,"H",28,"O",2);
row("Compounds",1,"Terephthalic acid","C",8,"H",6,"O",4);
row("Compounds",1,"Taurine","C",2,"H",7,"N",1,"O",3);
row("Compounds",1,"Tartrazine","C",16,"H",9,"N",4,"Na",3,"O",9,"S",2);
row("Compounds",1,"Tartaric acid","C",4,"H",6,"O",6);
row("Compounds",1,"Tannic acid","C",76,"H",52,"O",46);
row("Compounds",1,"Tabun","C",5,"H",11,"N",2,"O",2);
row("Compounds",1,"Sulforhodamine B","C",27,"H",30,"N",2,"O",7,"S",2);
row("Compounds",1,"Sulfanilic acid","C",6,"H",7,"N",1,"O",3);
row("Compounds",1,"Sulfanilamide","C",6,"H",8,"N",2,"O",2);
row("Compounds",1,"Sucrose (Sugar)","C",12,"H",22,"O",11);
row("Compounds",1,"Succinic anhydride","C",4,"H",4,"O",3);
row("Compounds",1,"Styrene","C",8,"H",8);
row("Compounds",1,"Strychnine","C",21,"H",22,"N",2,"O",2);
row("Compounds",1,"Stearic acid","C",18,"H",36,"O",2);
row("Compounds",1,"Squalene","C",30,"H",50,);
row("Compounds",1,"Spermidine","C",6,"H",8,"O",3);
row("Compounds",1,"Sotolone","C",6,"H",8,"O",2);
row("Compounds",1,"Skatole","C",9,"H",9);
row("Compounds",1,"Sildenafil","C",22,"H",30,"N",6,"O",4);
row("Compounds",1,"Siamenoside","C",54,"H",92,"O",24);
row("Compounds",1,"Shikimic acid","C",7,"H",10,"O",5);
row("Compounds",1,"Serotonin","C",10,"H",12,"N",2);
row("Compounds",1,"Serine","C",5,"H",11,"N",1,"O",2,"Se",1);
row("Compounds",1,"Selenomethionine","C",5,"H",11,"N",1,"O",2,"Se",1);
row("Compounds",1,"Selenocysteine","C",3,"H",7,"N",1,"O",2,"Se",1);
row("Compounds",1,"Sebacoyl chloride","C",10,"H",16,"Cl",2,"O",2);
row("Compounds",1,"Sebacic acid","C",10,"H",18,"O",4);
row("Compounds",1,"Sarin","C",4,"H",10,"F",1,"O",2);
row("Compounds",1,"Salvinorin A","C",23,"H",28,"O",8);
row("Compounds",1,"Salicylic acid","C",7,"H",6,"O",3);
row("Compounds",1,"Salicylaldehyde","C",7,"H",6,"O",2);
row("Compounds",1,"Salicin","C",13,"H",18,"O",7);
row("Compounds",1,"Safrole","C",10,"H",10,"O",2);
row("Compounds",1,"Saccharin","C",7,"H",5,"N",1,"O",3);
row("Compounds",1,"Rotenone","C",23,"H",22,"O",6);
row("Compounds",1,"Rosolic acid","C",19,"H",14,"O",3);
row("Compounds",1,"Ribose","C",5,"H",10,"O",5);
row("Compounds",1,"Ribonucleic acid (RNA)","R",123,"C",1010101,"H",101010101,"N",101010101,"O",101101010,"P",101010101);
row("Compounds",1,"Riboflavin (Vitamin B2)","C",17,"H",20,"N",4,"O",6);
row("Compounds",1,"Retinol (Vitamin A)","C",20,"H",30);
row("Compounds",1,"Resorcinol","C",6,"H",6,"O",2);
row("Compounds",1,"Raffinose","C",18,"H",32,"O",16);
row("Compounds",1,"Quinoxaline","C",8,"H",6,"N",2);
row("Compounds",1,"Quinoline","C",9,"H",7);
row("Compounds",1,"Quinine","C",20,"H",24,"N",2,"O",2);
row("Compounds",1,"Quinazoline","C",8,"H",6,"N",2);
row("Compounds",1,"Quinaldine","C",10,"H",9);
row("Compounds",1,"Pyruvic acid","C",3,"H",4,"O",3);
row("Compounds",1,"Pyrrolidine","C",4,"H",9);
row("Compounds",1,"Pyrrole","C",4,"H",5);
row("Compounds",1,"Pyroglutamic acid","C",5,"H",7,"N",1,"O",3);
row("Compounds",1,"Pyrocatechol","C",12,"H",13,"Cl",1,"N",4);
row("Compounds",1,"Pyrimidine","C",4,"H",4,"N",2);
row("Compounds",1,"Pyrimethamine","C",12,"H",13,"Cl",1,"N",4);
row("Compounds",1,"Pyrilamine","C",17,"H",23,"N",3);
row("Compounds",1,"Pyridoxine (Vitamin B6)","C",8,"H",11,"N",1,"O",3);
row("Compounds",1,"Pyridoxal","C",8,"H",9,"N",1,"O",3);
row("Compounds",1,"Pyridine","C",5,"H",5);
row("Compounds",1,"Pyridazine","C",4,"H",4,"N",2);
row("Compounds",1,"Pyrene","C",16,"H",10);
row("Compounds",1,"Pyrazole","C",3,"H",4,"N",2);
row("Compounds",1,"Pyrazine","C",4,"H",12,"N",2);
row("Compounds",1,"Putrescine","C",4,"H",12,"N",2);
row("Compounds",1,"Purine","C",5,"H",4,"N",4);
row("Compounds",1,"Proton-sponge","C",14,"H",18,"N",2);
row("Compounds",1,"Propoxur","C",11,"H",15,"N",1,"O",3);
row("Compounds",1,"Propionitrile","C",3,"H",5);
row("Compounds",1,"Propionaldehyde","C",3,"H",6);
row("Compounds",1,"Propiolic acid","C",3,"H",2,"O",2);
row("Compounds",1,"Propiconazole","C",15,"H",17,"Cl",1,"N",3,"O",2);
row("Compounds",1,"Propargyl alcohol","C",3,"H",4);
row("Compounds",1,"Propanoic acid","C",3,"H",6,"O",2);
row("Compounds",1,"Propane","C",3,"H",8);
row("Compounds",1,"Proline","C",5,"H",9,"N",1,"O",2);
row("Compounds",1,"Progesterone","C",21,"H",30,"O",2);
row("Compounds",1,"Procaine","C",13,"H",20,"N",2,"O",2);
row("Compounds",1,"Primaquine","C",15,"H",21,"N",3);
row("Compounds",1,"Prednisone","C",21,"H",26,"O",5);
row("Compounds",1,"Potassium clavulanate","C",8,"H",8,"K",1,"O",1,"N",5);
row("Compounds",1,"Potassium 2-ethyl hexanoate","C",8,"H",15,"K",1,"O",2);
row("Compounds",1,"Polyvinylpyrrolidone (PVP)","C",6,"H",9,"N",1,"O",1);
row("Compounds",1,"Polyvinylidene fluoride (PVDF)","C",2,"H",2);
row("Compounds",1,"Polyvinylidene chloride","C",2,"H",2,"Cl",2);
row("Compounds",1,"Polyvinyl alcohol","C",2,"H",4);
row("Compounds",1,"Polyvinyl acetate","C",4,"H",6,"O",2);
row("Compounds",1,"Polypropylene","C",3,"H",6);
row("Compounds",1,"Polyethylenimine","C",4,"H",8);
row("Compounds",1,"Polyethylene terephthalate","C",10,"H",8,"O",4);
row("Compounds",1,"Piperylene","C",5,"H",8);
row("Compounds",1,"Piperonal","C",8,"H",6,"O",3);
row("Compounds",1,"Piperidine","C",5,"H",11);
row("Compounds",1,"Piperazine","C",4,"H",10,"N",2);
row("Compounds",1,"Pinacol","C",6,"H",14,"O",2);
row("Compounds",1,"Pimelic acid","C",7,"H",12,"O",4);
row("Compounds",1,"Picric acid","C",6,"H",3,"N",3,"O",7);
row("Compounds",1,"Phytic acid","C",6,"H",18,"O",24,"P",6);
row("Compounds",1,"Phthalic anhydride","C",8,"H",6,"O",2);
row("Compounds",1,"Phthalic acid","C",8,"H",6,"O",2);
row("Compounds",1,"Phorate","C",8,"H",4,"O",3);
row("Compounds",1,"Phloroglucinol","C",6,"H",6,"O",3);
row("Compounds",1,"Phenylhydroxylamine","C",6,"H",7,"N",1,"O",1);
row("Compounds",1,"Phenylhydrazine","C",6,"H",8,"N",2);
row("Compounds",1,"Phenylalanine","C",9,"H",11,"N",1,"O",2);
row("Compounds",1,"Phenylacetylene","C",8,"H",6);
row("Compounds",1,"Phenylacetic acid","C",8,"H",8,"O",2);
row("Compounds",1,"Phenothiazine","C",12,"H",9,"NS",1);
row("Compounds",1,"Phenolphthalein","C",20,"H",14,"O",4);
row("Compounds",1,"Phenol","C",6,"H",6);
row("Compounds",1,"Phenol red","C",19,"H",14,"O",5);
row("Compounds",1,"Phenobarbital","C",12,"H",12,"N",2,"O",3);
row("Compounds",1,"Phenethylamine","C",8,"H",11);
row("Compounds",1,"Phencyclidine","C",17,"H",25);
row("Compounds",1,"Phenanthrene","C",14,"H",10);
row("Compounds",1,"Phenacyl bromide","C",8,"H",7,"Br",1);
row("Compounds",1,"Phenacetin","C",10,"H",13,"N",1,"O",2);
row("Compounds",1,"Perylene","C",20,"H",12);
row("Compounds",1,"Peroxyacetic acid","C",2,"H",4,"O",3);
row("Compounds",1,"Permethrin","C",21,"H",20,"Cl",1,"O",3);
row("Compounds",1,"Pentetic acid","C",14,"H",23,"N",3,"O",10);
row("Compounds",1,"Pentane","C",5,"H",12);
row("Compounds",1,"Pentafluoroethane","C",2,"H",1,"F",5);
row("Compounds",1,"Pentaerythritol","C",4,"H",10,"O",3);
row("Compounds",1,"Pentadecane","C",6,"H",12,"O",4);
row("Compounds",1,"Pentachlorophenol","C",6,"H",1,"Cl",5);
row("Compounds",1,"Pentachlorobiphenyl","C",12,"H",10,"Cl",1);
row("Compounds",1,"Pentabromodiphenyl ether","C",12,"H",5,"Br",5);
row("Compounds",1,"Pelargonic acid","C",9,"H",18,"O",2);
row("Compounds",1,"Parathion","C",10,"H",14,"N",1,"O",5,"P",1,"S",1);
row("Compounds",1,"Paraformaldehyde","C",100,"H",2000,"O",100);
row("Compounds",1,"Parachlorometaxylenol (PCMX)","C",8,"H",9,"Cl",1);
row("Compounds",1,"Para red","C",16,"H",11,"N",3,"O",3);
row("Compounds",1,"Pantothenic acid (Vitamin B5)","C",9,"H",17,"N",1,"O",5);
row("Compounds",1,"Palmitic acid","C",16,"H",32,"O",2);
row("Compounds",1,"Paclitaxel","C",47,"H",51,"N",1,"O",14);
row("Compounds",1,"PABA","C",7,"H",7,"N",1,"O",2);
row("Compounds",1,"p-Toluic acid","C",8,"H",8,"O",2);
row("Compounds",1,"p-Toluenesulfonic acid","C",7,"H",8,"O",3);
row("Compounds",1,"p-Phenylenediamine","C",6,"H",8,"N",2);
row("Compounds",1,"p-Dichlorobenzene","C",6,"H",4,"Cl",2);
row("Compounds",1,"p-Aminobenzoic acid (PABA)","C",7,"H",7,"N",1,"O",2);
row("Compounds",1,"Oxymetholone","C",21,"H",32,"O",3);
row("Compounds",1,"Oxolinic acid","C",13,"H",11,"N",1,"O",5);
row("Compounds",1,"Oxazole","C",3,"H",3,"N",1,"O",1);
row("Compounds",1,"Oxamide","C",2,"H",4,"N",2,"O",2);
row("Compounds",1,"Oxalic acid","C",2,"H",2,"O",4);
row("Compounds",1,"Orotic acid","C",5,"H",4,"N",2,"O",4);
row("Compounds",1,"Ornithine","C",5,"H",12,"N",2,"O",2);
row("Compounds",1,"Orcinol","C",7,"H",8,"O",2);
row("Compounds",1,"Orcin","C",7,"H",8,"O",2);
row("Compounds",1,"Oleic acid","C",18,"H",34,"O",2);
row("Compounds",1,"Octanoic acid","C",8,"H",16,"O",2);
row("Compounds",1,"Octane","C",8,"H",18);
row("Compounds",1,"Octabromodiphenyl ether","C",12,"H",2,"Br",8);
row("Compounds",1,"o-Toluic acid","C",8,"H",8,"O",2);
row("Compounds",1,"Norcarane","C",7,"H",12);
row("Compounds",1,"Noradrenaline","C",8,"H",11,"N",1,"O",3);
row("Compounds",1,"Nonoxynol-9","C",33,"H",60,"O",10);
row("Compounds",1,"Nonane","C",9,"H",20);
row("Compounds",1,"Nonacosane","C",29,"H",60);
row("Compounds",1,"Nitrosobenzene","C",6,"H",5,"N",1,"O",1);
row("Compounds",1,"Nitromethane","C",1,"H",3,"N",1,"O",2);
row("Compounds",1,"Nitroglycerine","C",3,"H",5,"N",3,"O",9);
row("Compounds",1,"Nitrofurantoin","C",8,"H",6,"N",4,"O",5);
row("Compounds",1,"Nitroethane","C",2,"H",5,"N",1,"O",2);
row("Compounds",1,"Nitrobenzene","C",6,"H",5,"N",1,"O",2);
row("Compounds",1,"Nitrilotriacetic acid","C",6,"H",9,"N",1,"O",6);
row("Compounds",1,"Nimesulide","C",13,"H",12,"N",2,"O",5);
row("Compounds",1,"Nile red","C",20,"H",18,"N",2,"O",2);
row("Compounds",1,"Niflumic acid","C",13,"H",9,"F",3,"N",2,"O",2);
row("Compounds",1,"Nicotine","C",10,"H",14,"N",2);
row("Compounds",1,"Niacin (Vitamin B3)","C",6,"H",5,"N",1,"O",2);
row("Compounds",1,"Neomycin","C",23,"H",46,"N",6,"O",13);
row("Compounds",1,"Naphthoquinone (Vitamin K)","C",10,"H",6,"O",2);
row("Compounds",1,"Naphthalene","C",10,"H",8);
row("Compounds",1,"N-Nitroso-N-methylurea","C",2,"H",5,"N",3,"O",2);
row("Compounds",1,"N-Methylpyrrolidone","C",5,"H",9,"N",1,"O",1);
row("Compounds",1,"n-Butylamine(Butylamine)","C",4,"H",11);
row("Compounds",1,"N-Acetylglutamate","C",7,"H",11,"O",5,"N",1);
row("Compounds",1,"N N-dimethylformamide","C",3,"H",7,"N",1,"O",1);
row("Compounds",1,"N N-Dimethylaniline","C",8,"H",11);
row("Compounds",1,"N N-Dimethylacetamide","C",4,"H",9,"N",1,"O",1);
row("Compounds",1,"Myrcene","C",10,"H",16);
row("Compounds",1,"Mustard gas","C",4,"H",8,"Cl",2);
row("Compounds",1,"Murexide","C",8,"H",8,"N",6,"O",6);
row("Compounds",1,"Morpholine","C",4,"H",9,"N",1,"O",1);
row("Compounds",1,"Mordant red 19","C",16,"H",13,"Cl",1,"N",4,"O",5);
row("Compounds",1,"Monosodium glutamate","C",5,"H",8,"N",1,"Na",1,"O",4);
row("Compounds",1,"Monocrotophos","C",7,"H",14,"N",1,"O",5);
row("Compounds",1,"Milrinone","C",12,"H",9,"N",3);
row("Compounds",1,"Michler's ketone","C",17,"H",20,"N",2);
row("Compounds",1,"Metronidazole","C",6,"H",9,"N",3,"O",3);
row("Compounds",1,"Metoprolol","C",15,"H",25,"N",1,"O",3);
row("Compounds",1,"Methylmercury","C",1,"H",3,"Hg",1);
row("Compounds",1,"Methylene blue","C",16,"H",18,"Cl",1,"N",3);
row("Compounds",1,"Methylcyclohexane","C",7,"H",14);
row("Compounds",1,"Methylamine","C",1,"H",5);
row("Compounds",1,"Methylal","C",3,"H",8,"O",2);
row("Compounds",1,"Methyl tert-butyl ether","C",5,"H",12);
row("Compounds",1,"Methyl methacrylate","C",5,"H",8,"O",2);
row("Compounds",1,"Methyl isocyanate","C",2,"H",3,"N",1,"O",1);
row("Compounds",1,"Methyl isobutyl ketone","C",6,"H",12);
row("Compounds",1,"Methyl cyanoacrylate","C",5,"H",5,"N",1,"O",2);
row("Compounds",1,"Methyl acetate","C",3,"H",6,"O",2);
row("Compounds",1,"Methoxyflurane","C",3,"H",4,"Cl",2,"F",2);
row("Compounds",1,"Methoxychlor","C",16,"H",15,"Cl",1,"O",2);
row("Compounds",1,"Methomyl","C",5,"H",10,"N",2,"O",2);
row("Compounds",1,"Methionine","C",5,"H",11,"N",1,"O",2);
row("Compounds",1,"Methanol","C",1,"H",4);
row("Compounds",1,"Methanesulfonic acid","C",1,"H",4,"O",3);
row("Compounds",1,"Methane","C",1,"H",4);
row("Compounds",1,"Metamizole (dipyrone)","C",13,"H",16,"N",3,"Na",1,"O",4);
row("Compounds",1,"Metaldehyde","C",8,"H",16,"O",4);
row("Compounds",1,"Meta-chloroperoxybenzoic acid","C",7,"H",5,"Cl",1,"O",3);
row("Compounds",1,"Mesotartaric acid","C",4,"H",6,"O",6);
row("Compounds",1,"Mesityl oxide","C",6,"H",10);
row("Compounds",1,"Merocyanine","C",26,"H",32,"N",3,"Na",1,"O",7);
row("Compounds",1,"Menthol","C",10,"H",20);
row("Compounds",1,"Meloxicam","C",14,"H",13,"N",3,"O",4,"S",2);
row("Compounds",1,"Melatonin","C",13,"H",16,"N",2,"O",2);
row("Compounds",1,"MEK","C",4,"H",8);
row("Compounds",1,"Mecoprop","C",10,"H",11,"Cl",1,"O",3);
row("Compounds",1,"MDMA","C",11,"H",15,"N",1,"O",2);
row("Compounds",1,"Mauveine","C",26,"H",23,"N",4);
row("Compounds",1,"Mannose","C",6,"H",12,"O",6);
row("Compounds",1,"Mandelonitrile","C",8,"H",7,"N",1,"O",1);
row("Compounds",1,"Maltose","C",12,"H",22,"O",11);
row("Compounds",1,"Malic acid","C",4,"H",6,"O",5);
row("Compounds",1,"Maleic anhydride","C",4,"H",2,"O",3);
row("Compounds",1,"Malathion","C",10,"H",19,"O",6,"P",1,"S",2);
row("Compounds",1,"Malachite green","C",23,"H",25,"Cl",1,"N",2);
row("Compounds",1,"Lysine","C",6,"H",14,"N",2,"O",2);
row("Compounds",1,"Lycopene","C",40,"H",56);
row("Compounds",1,"Luminol","C",8,"H",7,"N",3,"O",2);
row("Compounds",1,"LSD","C",20,"H",25,"N",3);
row("Compounds",1,"Loratadine","C",22,"H",23,"Cl",1,"N",2,"O",2);
row("Compounds",1,"Lipoamide","C",8,"H",15,"N",1,"O",1,"S",2);
row("Compounds",1,"Linolenic acid","C",18,"H",30,"O",2);
row("Compounds",1,"Linoleic acid","C",18,"H",32,"O",2);
row("Compounds",1,"Linalool","C",10,"H",18);
row("Compounds",1,"Limonene","C",10,"H",16);
row("Compounds",1,"Levulinic acid","C",5,"H",8,"O",3);
row("Compounds",1,"Leucine","C",6,"H",13,"N",1,"O",2);
row("Compounds",1,"LDA (Lithium diisopropylamide)","C",6,"H",14,"Li",1);
row("Compounds",1,"Lauryl alcohol","C",12,"H",26);
row("Compounds",1,"Lauric acid","C",12,"H",24,"O",2);
row("Compounds",1,"Lactose","C",12,"H",22,"O",11);
row("Compounds",1,"Lactic acid","C",3,"H",6,"O",3);
row("Compounds",1,"Kojic acid","C",6,"H",6,"O",4);
row("Compounds",1,"Kanamycin","C",18,"H",36,"N",4,"O",11);
row("Compounds",1,"Jasmone","C",11,"H",16);
row("Compounds",1,"Itraconazole","C",35,"H",38,"Cl",1,"N",8,"O",4);
row("Compounds",1,"Isoxazole","C",3,"H",3,"N",1,"O",1);
row("Compounds",1,"Isoquinoline","C",9,"H",7);
row("Compounds",1,"Isophthalic acid","C",8,"H",4,"O",2);
row("Compounds",1,"Isooctanol","C",8,"H",18);
row("Compounds",1,"Isoleucine","C",6,"H",13,"N",1,"O",2);
row("Compounds",1,"Isoindole","C",8,"H",7);
row("Compounds",1,"Isoflurane","C",3,"H",2,"Cl",1,"F",5);
row("Compounds",1,"Isoborneol","C",10,"H",18);
row("Compounds",1,"Isobenzofuran","C",8,"H",6);
row("Compounds",1,"Isatin","C",8,"H",5,"N",1,"O",2);
row("Compounds",1,"Ionone","C",13,"H",20);
row("Compounds",1,"Inositol","C",6,"H",12,"O",6);
row("Compounds",1,"Indoline","C",8,"H",9);
row("Compounds",1,"Indole-3-acetic acid","C",10,"H",9,"N",1,"O",2);
row("Compounds",1,"Indole","C",8,"H",7);
row("Compounds",1,"Indigo dye","C",16,"H",10,"N",2,"O",2);
row("Compounds",1,"Indene","C",9,"H",8);
row("Compounds",1,"Indazole","C",7,"H",6,"N",2);
row("Compounds",1,"Imiquimod","C",14,"H",16,"N",4);
row("Compounds",1,"Imidazole","C",3,"H",4,"N",2);
row("Compounds",1,"Ibuprofen","C",13,"H",18,"O",2);
row("Compounds",1,"Hygrine","C",8,"H",15,"N",1,"O",1);
row("Compounds",1,"Hydroxyproline","C",5,"H",9,"N",1,"O",3);
row("Compounds",1,"Hydroquinone","C",6,"H",6);
row("Compounds",1,"Hydrochlorothiazide","C",7,"H",8,"Cl",1,"N",3,"O",4,"S",2);
row("Compounds",1,"Homotaurine","C",3,"H",9,"N",1,"O",3);
row("Compounds",1,"Homocystine","C",4,"H",9,"N",1,"O",2);
row("Compounds",1,"Homocysteine","C",4,"H",9,"N",1,"O",2);
row("Compounds",1,"Histidine","C",6,"H",9,"N",3,"O",2);
row("Compounds",1,"Histamine","C",5,"H",9,"N",3);
row("Compounds",1,"Hippuric acid","C",9,"H",9,"N",1,"O",3);
row("Compounds",1,"Hexanoic acid","C",6,"H",12,"O",2);
row("Compounds",1,"Hexanitrodiphenylamine","C",12,"H",5,"N",7,"O",12);
row("Compounds",1,"Hexane","C",6,"H",14);
row("Compounds",1,"Hexamethyldisilazane","C",6,"H",19,"N",1,"Si",2);
row("Compounds",1,"Hexafluoropropylene","C",3,"F",6);
row("Compounds",1,"Hexafluoroethane","C",2,"F",6);
row("Compounds",1,"Hexafluoro-2-propanone","C",3,"F",6);
row("Compounds",1,"Hexafluoro-2-propanol","C",3,"H",2,"F",6);
row("Compounds",1,"Hexadecane","C",16,"H",34);
row("Compounds",1,"Hexabromocyclododecane","C",12,"H",18,"Br",6);
row("Compounds",1,"Heptane","C",7,"H",16);
row("Compounds",1,"Heptadecane","C",17,"H",36);
row("Compounds",1,"HEPES","C",8,"H",18,"N",2,"O",4);
row("Compounds",1,"Heme o","C",49,"H",58,"O",5,"N",4,"Fe",1);
row("Compounds",1,"Heme c","C",34,"H",36,"O",4,"N",4,"S",2,"Fe",1);
row("Compounds",1,"Heme b","C",34,"H",32,"O",4,"N",4,"Fe",1);
row("Compounds",1,"Heme a","C",49,"H",56,"O",6,"N",4,"Fe",1);
row("Compounds",1,"Hematoxylin","C",16,"H",14,"O",6);
row("Compounds",1,"Halothane","C",2,"H",1,"Br",1,"Cl",1,"F",3);
row("Compounds",1,"Guanosine","C",10,"H",13,"N",5,"O",5);
row("Compounds",1,"Guanine","C",5,"H",5,"N",5);
row("Compounds",1,"Guanidine","C",1,"H",5,"N",3);
row("Compounds",1,"Guaiacol","C",7,"H",8,"O",2);
row("Compounds",1,"Glyoxal","C",2,"H",2,"O",2);
row("Compounds",1,"Glycolic acid","C",2,"H",4,"O",3);
row("Compounds",1,"Glycine","C",2,"H",5,"N",1,"O",2);
row("Compounds",1,"Glycidol","C",3,"H",6,"O",2);
row("Compounds",1,"Glycerophosphoric acid","C",3,"H",6,"O",2);
row("Compounds",1,"Glycerin (glycerol)","C",3,"H",8);
row("Compounds",1,"Glyburide","C",23,"H",28,"Cl",1,"N",3,"O",5);
row("Compounds",1,"Glutathione","C",10,"H",17,"N",3,"O",6);
row("Compounds",1,"Glutaric acid","C",5,"H",8,"O",4);
row("Compounds",1,"Glutaraldehyde","C",5,"H",8,"O",2);
row("Compounds",1,"Glutamine","C",5,"H",10,"N",2,"O",3);
row("Compounds",1,"Glutamic acid (glutamate)","C",5,"H",9,"N",1,"O",4);
row("Compounds",1,"Glucose","C",6,"H",12,"O",6);
row("Compounds",1,"Gluconic acid","C",6,"H",12,"O",7);
row("Compounds",1,"Gibberellic acid","C",19,"H",22,"O",6);
row("Compounds",1,"Geraniol","C",10,"H",18);
row("Compounds",1,"Gamma-hydroxybutyrate (GHB)","C",4,"H",8,"O",3);
row("Compounds",1,"Gamma-butyrolactone","C",4,"H",6,"O",2);
row("Compounds",1,"Gamma-aminobutyric acid","C",4,"H",9,"N",1,"O",2);
row("Compounds",1,"Galantamine","C",17,"H",21,"N",1,"O",3);
row("Compounds",1,"Galactose","C",6,"H",12,"O",6);
row("Compounds",1,"Gadopentetate (Magnevist)","C",28,"H",54,"Gd",1,"N",5,"O",20);
row("Compounds",1,"Furylfuramide","C",11,"H",8,"N",2,"O",5);
row("Compounds",1,"Furfurylamine","C",5,"H",7,"N",1,"O",1);
row("Compounds",1,"Furfuryl alcohol","C",5,"H",6,"O",2);
row("Compounds",1,"Furfural","C",5,"H",4,"O",2);
row("Compounds",1,"Furan (furane)","C",4,"H",4);
row("Compounds",1,"Fumaric acid","C",4,"H",4,"O",4);
row("Compounds",1,"Fullerene","C",60,);
row("Compounds",1,"Fructose","C",6,"H",12,"O",6);
row("Compounds",1,"Formoterol","C",19,"H",24,"N",2,"O",4);
row("Compounds",1,"Formic acid","C",1,"H",2,"O",2);
row("Compounds",1,"Formamide","C",1,"H",3,"N",1,"O",1);
row("Compounds",1,"Formaldehyde","C",1,"H",2);
row("Compounds",1,"Folic acid (Vitamin M)","C",19,"H",19,"N",7,"O",6);
row("Compounds",1,"Fluoxetine","C",17,"H",18,"F",3,"N",1,"O",1);
row("Compounds",1,"Fluoroethylene","C",2,"H",3);
row("Compounds",1,"Fluorobenzene","C",6,"H",5);
row("Compounds",1,"Fluorescein","C",20,"H",12,"O",5);
row("Compounds",1,"Fluorene","C",13,"H",10);
row("Compounds",1,"Fluoranthene","C",16,"H",10);
row("Compounds",1,"Flunixin","C",14,"H",11,"F",3,"N",2,"O",2);
row("Compounds",1,"Fipronil","C",12,"Cl",1,"S",2,"F",6,"N",4,"Os",1);
row("Compounds",1,"Ferrocene","C",10,"H",10,"Fe",1);
row("Compounds",1,"Farnesol","C",15,"H",26);
row("Compounds",1,"Eugenol","C",10,"H",12,"O",2);
row("Compounds",1,"Ethynol","C",2,"H",2);
row("Compounds",1,"Ethylene oxide","C",2,"H",4);
row("Compounds",1,"Ethylbenzene","C",8,"H",10);
row("Compounds",1,"Ethylamine","C",2,"H",7);
row("Compounds",1,"Ethyl formate","C",3,"H",6,"O",2);
row("Compounds",1,"Ethyl acetate","C",4,"H",8,"O",2);
row("Compounds",1,"Ethyl p-aminobenzoate","C",9,"H",11,"N",1,"O",2);
row("Compounds",1,"Ethenone","C",2,"H",2);
row("Compounds",1,"Ethene","C",2,"H",4);
row("Compounds",1,"Ethanol","C",2,"H",6);
row("Compounds",1,"Ethane","C",2,"H",6);
row("Compounds",1,"Estradiol","C",18,"H",24,"O",2);
row("Compounds",1,"Erythritol","C",4,"H",10,"O",4);
row("Compounds",1,"Erucic acid","C",22,"H",42);
row("Compounds",1,"Epinephrine","C",9,"H",13,"N",1,"O",3);
row("Compounds",1,"Epinephrine (adrenaline)","C",9,"H",13,"N",1,"O",3);
row("Compounds",1,"Ephedrine","C",10,"H",15,"N",1,"O",1);
row("Compounds",1,"Eosin","C",20,"H",8,"Br",1,"O",5,"Eo",1,"Y",1);
row("Compounds",1,"Endrin","C",12,"H",8,"Cl",6);
row("Compounds",1,"Endosulfan","C",9,"H",6,"Cl",1,"O",3);
row("Compounds",1,"Eicosane","C",20,"H",42);
row("Compounds",1,"Ethylenediamine-tetraacetic acid","C",10,"H",16,"N",2,"O",8);
row("Compounds",1,"Doxylamine succinate","C",17,"H",22,"N",2);
row("Compounds",1,"Dopamine","C",8,"H",11,"N",1,"O",2);
row("Compounds",1,"Domperidone","C",22,"H",24,"Cl",1,"N",5,"O",2);
row("Compounds",1,"Dodecylbenzene","C",18,"H",30);
row("Compounds",1,"Dodecane","C",12,"H",26);
row("Compounds",1,"Divinylbenzene","C",10,"H",10);
row("Compounds",1,"Diuron","C",9,"H",10,"Cl",1,"F",2,"N",2);
row("Compounds",1,"Dithranol","C",14,"H",10,"O",3);
row("Compounds",1,"Disulfoton","C",8,"H",19,"O",2,"P",1,"S",3);
row("Compounds",1,"Disulfiram","C",10,"H",20,"N",2,"S",4);
row("Compounds",1,"Direct Blue 1","C",34,"H",28,"N",6,"O",16,"S",4);
row("Compounds",1,"Diquat","C",12,"H",12,"Br",2,"N",2);
row("Compounds",1,"Diphenylmethanol (Benzhydrol)","C",13,"H",12);
row("Compounds",1,"Diphenylacetylene (Tolane)","C",14,"H",10);
row("Compounds",1,"Dioxin","C",4,"H",4,"O",2);
row("Compounds",1,"Dioxathion","C",12,"H",26,"O",6,"P",2,"S",4);
row("Compounds",1,"Dioxane","C",4,"H",8,"O",2);
row("Compounds",1,"Dioctyl phthalate","C",24,"H",38,"O",4);
row("Compounds",1,"Dinoseb","C",10,"H",12,"N",2,"O",5);
row("Compounds",1,"Dimethylmercury","C",2,"H",6,"Hg",1);
row("Compounds",1,"Dimethylglyoxime","C",4,"H",8,"N",2,"O",2);
row("Compounds",1,"Dimethyldiethoxysilane","C",6,"H",16,"O",2,"Si",1);
row("Compounds",1,"Dimethylamine","C",2,"H",7);
row("Compounds",1,"Dimethyl sulfoxide (DMSO)","C",2,"H",6,"OS",1);
row("Compounds",1,"Dimethyl ether (DME)","C",1,"H",3,"C",1,"O",3);
row("Compounds",1,"Diketene","C",4,"H",4,"O",2);
row("Compounds",1,"Diisopropyl ether","C",6,"H",14);
row("Compounds",1,"Diisoheptyl phthalate","C",22,"H",34,"O",4);
row("Compounds",1,"Dihydrocortisone","C",21,"H",30,"O",5);
row("Compounds",1,"Digitonin","C",56,"H",92,"O",29);
row("Compounds",1,"Difluoromethane","C",1,"H",2,"F",2);
row("Compounds",1,"Diethylenetriamine","C",4,"H",13,"N",3);
row("Compounds",1,"Diethylene glycol","C",4,"H",10,"O",3);
row("Compounds",1,"Diethylamine","C",4,"H",11);
row("Compounds",1,"Diethyl ether","C",4,"H",10);
row("Compounds",1,"Diethion","C",9,"H",22,"O",4,"P",2,"S",4);
row("Compounds",1,"Diethanolamine","C",4,"H",11,"N",1,"O",2);
row("Compounds",1,"Dieldrin","C",12,"H",8,"Cl",6);
row("Compounds",1,"Dicyclopentadiene","C",10,"H",12);
row("Compounds",1,"Dicrotophos","C",8,"H",16,"N",1,"O",5);
row("Compounds",1,"Dicofol","C",14,"H",9,"Cl",5);
row("Compounds",1,"Diclofenac sodium","C",14,"H",11,"Cl",2,"N",1,"O",2);
row("Compounds",1,"Dichlorvos","C",4,"H",7,"Cl",2,"O",4);
row("Compounds",1,"Dichlorotrifluoroethane","C",2,"H",1,"Cl",2,"F",3);
row("Compounds",1,"Dichlorophen","C",13,"H",10,"Cl",2,"O",2);
row("Compounds",1,"Dichlorofluoromethane","C",1,"H",1,"Cl",2);
row("Compounds",1,"Dichlorodimethylsilane","C",2,"H",6,"Cl",2,"Si",1);
row("Compounds",1,"Dichlorodifluoromethane","C",1,"Cl",2,"F",2);
row("Compounds",1,"Dichlorobutane","C",4,"H",8,"Cl",2);
row("Compounds",1,"Dichloroacetic acid","C",2,"H",2,"Cl",2,"O",2);
row("Compounds",1,"Diazomethane","C",1,"H",2,"N",2);
row("Compounds",1,"Diazinon","C",12,"H",21,"N",2,"O",3,"PS",1);
row("Compounds",1,"Diacetylene","C",4,"H",2);
row("Compounds",1,"Di-t-butyl peroxide","C",8,"H",18,"O",2);
row("Compounds",1,"Dexamethazone","C",22,"H",29,"F",1,"O",5);
row("Compounds",1,"Deoxyribonucleic Acid (DNA)","C",1010101,"H",101010101,"N",101010101,"O",101101010,"P",101010101);
row("Compounds",1,"Denatonium","C",28,"H",34,"N",2,"O",3);
row("Compounds",1,"Demeton","C",8,"H",19,"O",3,"P",1,"S",2);
row("Compounds",1,"Deltamethrin","C",22,"H",19,"Br",2,"N",1,"O",3);
row("Compounds",1,"Dehydrocholic acid","C",24,"H",34,"O",5);
row("Compounds",1,"Decahydronaphthalene","C",10,"H",18);
row("Compounds",1,"Decabromodiphenyl ether","C",12,"Br",10);
row("Compounds",1,"DDT","C",14,"H",9,"Cl",5);
row("Compounds",1,"DABCO","C",6,"H",12,"N",2);
row("Compounds",1,"Cytosine","C",4,"H",5,"N",3);
row("Compounds",1,"Cystine","C",6,"H",12,"N",2,"O",4,"S",2);
row("Compounds",1,"Cysteine","C",3,"H",7,"N",1,"O",2);
row("Compounds",1,"Cysteamine","C",2,"H",7,"NS",1);
row("Compounds",1,"Cypermethrin","C",22,"H",19,"Cl",1,"N",1,"O",3);
row("Compounds",1,"Cycrimine","C",19,"H",29,"N",1,"O",1);
row("Compounds",1,"Cyclopentene","C",5,"H",8);
row("Compounds",1,"Cyclopentanone","C",5,"H",8);
row("Compounds",1,"Cyclopentanol","C",5,"H",10);
row("Compounds",1,"Cyclopentane","C",5,"H",10);
row("Compounds",1,"Cyclooctatetraene","C",8,"H",8);
row("Compounds",1,"Cyclonite","C",3,"H",6,"N",6,"O",6);
row("Compounds",1,"Cyclohexene","C",6,"H",10);
row("Compounds",1,"Cyclohexanone","C",6,"H",10);
row("Compounds",1,"Cyclohexanol","C",6,"H",12);
row("Compounds",1,"Cyclohexane","C",6,"H",12);
row("Compounds",1,"Cycloheptatriene","C",7,"H",8);
row("Compounds",1,"Cyclododecane","C",12,"H",24);
row("Compounds",1,"Cyclodecane","C",10,"H",20);
row("Compounds",1,"Cyanuric acid","C",3,"H",3,"N",3,"O",3);
row("Compounds",1,"Cyanoguanidine","C",2,"H",4,"N",4);
row("Compounds",1,"Cyanogen","C",2,"N",2);
row("Compounds",1,"Cuscohygrine","C",13,"H",24,"N",2);
row("Compounds",1,"Cupferron","C",6,"H",9,"N",3,"O",2);
row("Compounds",1,"Cuneane","C",8,"H",8);
row("Compounds",1,"Cumene","C",9,"H",12);
row("Compounds",1,"Cubane","C",8,"H",8);
row("Compounds",1,"Crystal violet","C",24,"H",28,"N",3,"Cl",1);
row("Compounds",1,"Crotonaldehyde","C",4,"H",6);
row("Compounds",1,"Cresyl violet","C",19,"H",18,"Cl",1,"N",3);
row("Compounds",1,"Cresol","C",7,"H",8);
row("Compounds",1,"Creatine","C",4,"H",9,"N",3,"O",2);
row("Compounds",1,"Coumarin","C",9,"H",6,"O",2);
row("Compounds",1,"Coronene","C",24,"H",12);
row("Compounds",1,"Coomassie blue","C",47,"H",50,"N",3,"O",7,"S",2);
row("Compounds",1,"Coniine","C",8,"H",17);
row("Compounds",1,"Congo red","C",32,"H",22,"N",6,"Na",2,"O",6,"S",2);
row("Compounds",1,"Colchicine","C",22,"H",25,"N",1,"O",6);
row("Compounds",1,"Cocamidopropyl","C",19,"H",38,"N",2,"O",3);
row("Compounds",1,"Cobalamin (Vitamin B12)","C",63,"H",88,"Co",1,"N",14,"O",14);
row("Compounds",1,"Cloxacillin","C",19,"H",18,"Cl",1,"N",3,"O",5);
row("Compounds",1,"Clopidol","C",7,"H",7,"Cl",2,"N",1,"O",1);
row("Compounds",1,"Clobetasone","C",22,"H",26,"Cl",1,"F",1,"O",4);
row("Compounds",1,"Citrulline","C",6,"H",13,"N",3,"O",3);
row("Compounds",1,"Citronellal","C",10,"H",18);
row("Compounds",1,"Citric acid","C",6,"H",8,"O",7);
row("Compounds",1,"Citral","C",10,"H",16);
row("Compounds",1,"cis-3-Hexenal","C",6,"H",10);
row("Compounds",1,"cis-3-Hexen-1-ol","C",6,"H",12);
row("Compounds",1,"cis-3-Hexen-1-ol","C",6,"H",12);
row("Compounds",1,"cis-3-Hexanal","C",6,"H",10);
row("Compounds",1,"cis-2-butene","C",4,"H",8);
row("Compounds",1,"Cinnoline","C",4,"H",4,"N",2);
row("Compounds",1,"Cinnamyl alcohol","C",9,"H",10);
row("Compounds",1,"Cinnamic acid","C",9,"H",8,"O",2);
row("Compounds",1,"Cinnamaldehyde","C",9,"H",8);
row("Compounds",1,"Cinchonine","C",19,"H",22,"N",2);
row("Compounds",1,"Cilostazol","C",20,"H",27,"N",5,"O",2);
row("Compounds",1,"Chromotropic acid","C",10,"H",8,"O",8,"S",2);
row("Compounds",1,"Choline","C",5,"H",14,"N",1,"O",1);
row("Compounds",1,"Cholesterol","C",27,"H",46);
row("Compounds",1,"Chlorthiamide","C",7,"H",5,"Cl",1,"N",2,"S",1);
row("Compounds",1,"Chlorpyrifos","C",9,"Cl",3,"N",1,"O",3,"P",1,"S",1);
row("Compounds",1,"Chloroxuron","C",15,"H",15,"Cl",1,"N",2,"O",2);
row("Compounds",1,"Chlorotrimethylsilane","C",3,"H",9,"Si",1,"Cl",1);
row("Compounds",1,"Chlorotrifluoromethane","C",1,"Cl",1,"F",3);
row("Compounds",1,"Chlorothiazide","C",7,"H",6,"Cl",1,"N",3,"O",4,"S",2);
row("Compounds",1,"Chlorostyrene","C",8,"H",7,"Cl",1);
row("Compounds",1,"Chloroquine","C",18,"H",26,"Cl",1,"N",3);
row("Compounds",1,"Chloroprene","C",4,"H",5,"Cl",1);
row("Compounds",1,"Chloropicrin","C",1,"Cl",3,"N",1,"O",2);
row("Compounds",1,"Chloropentafluoroethane","C",2,"Cl",1,"F",5);
row("Compounds",1,"Chloromethane","C",1,"H",3,"Cl",1);
row("Compounds",1,"Chloroform","C",1,"H",1,"Cl",3);
row("Compounds",1,"Chlorofluoromethane","C",1,"H",2,"Cl",1);
row("Compounds",1,"Chloroethene","C",2,"H",3,"Cl",1);
row("Compounds",1,"Chlorodifluoromethane","C",1,"H",1,"Cl",1,"F",2);
row("Compounds",1,"Chlorobenzene","C",6,"H",5,"Cl",1);
row("Compounds",1,"Chloroacetic acid","C",2,"H",3,"Cl",1,"O",2);
row("Compounds",1,"Chloro-m-cresol","C",7,"H",7,"Cl",1);
row("Compounds",1,"Chlorhexidine gluconate","C",22,"H",30,"Cl",2,"N",10);
row("Compounds",1,"Chlordane","C",10,"H",6,"Cl",8);
row("Compounds",1,"Chloranilic acid","C",6,"H",2,"Cl",2,"O",4);
row("Compounds",1,"Chloramphenicol","C",11,"H",12,"Cl",2,"N",2,"O",5);
row("Compounds",1,"Chloramine-T","C",7,"H",7,"Cl",1,"N",1,"Si",1,"Na",3);
row("Compounds",1,"Chlorambucil","C",14,"H",19,"Cl",2,"N",1,"O",2);
row("Compounds",1,"Chloral","C",2,"H",1,"Cl",3);
row("Compounds",1,"Chloral hydrate","C",2,"H",2,"Cl",3,"O",2);
row("Compounds",1,"Cetyl alcohol","C",16,"H",34);
row("Compounds",1,"Ceftriaxone","C",18,"H",18,"N",8,"O",7,"S",3);
row("Compounds",1,"Cefotaxime","C",16,"H",17,"N",5,"O",7,"S",2);
row("Compounds",1,"Cefazolin","C",14,"H",14,"N",8,"O",4,"S",3);
row("Compounds",1,"Castor oil","C",6,"H",6,"O",2);
row("Compounds",1,"Carvone","C",10,"H",14);
row("Compounds",1,"Carvacrol","C",10,"H",14);
row("Compounds",1,"Cartap","C",7,"H",16,"Cl",1,"N",3,"O",2,"S",2);
row("Compounds",1,"Carnitine","C",7,"H",15,"N",1,"O",3);
row("Compounds",1,"Carminic acid","C",22,"H",20,"O",13);
row("Compounds",1,"Carboxypolymethylene","C",3,"H",4,"O",2);
row("Compounds",1,"Carboplatin","C",6,"H",14,"N",2,"O",4,"Pt",1);
row("Compounds",1,"Carbonyl fluoride","CO",1,"F",2);
row("Compounds",1,"Carbofuran","C",12,"H",15,"N",1,"O",3);
row("Compounds",1,"Carbazole","C",12,"H",9);
row("Compounds",1,"Captopril","C",9,"H",15,"N",1,"O",3);
row("Compounds",1,"Captan","C",9,"H",8,"Cl",3,"N",1,"O",2);
row("Compounds",1,"Capsaicin","C",18,"H",27,"N",1,"O",3);
row("Compounds",1,"Caprolactone","C",6,"H",10,"O",2);
row("Compounds",1,"Caprolactam","C",6,"H",11,"N",1,"O",1);
row("Compounds",1,"Cannabinol","C",21,"H",26,"O",2);
row("Compounds",1,"Camphor","C",10,"H",16);
row("Compounds",1,"Camphene","C",10,"H",16);
row("Compounds",1,"Calcein","C",30,"H",26,"N",2,"O",13);
row("Compounds",1,"Caffeine","C",8,"H",10,"N",4,"O",2);
row("Compounds",1,"Cafestol","C",20,"H",28,"O",3);
row("Compounds",1,"Cadinene","C",15,"H",24);
row("Compounds",1,"Cacotheline","C",21,"H",21,"N",3,"O",7);
row("Compounds",1,"Cacodylic acid","C",2,"H",7,"As",1,"O",2);
row("Compounds",1,"Butyryl chloride","C",4,"H",7,"Cl",1);
row("Compounds",1,"Butyrophenone","C",10,"H",12);
row("Compounds",1,"Butyraldehyde","C",4,"H",8);
row("Compounds",1,"Butyllithium","C",4,"H",9,"Li",1);
row("Compounds",1,"Butene","C",4,"H",8);
row("Compounds",1,"Butane","C",4,"H",10);
row("Compounds",1,"Butadiene resin","C",4,"H",8);
row("Compounds",1,"Buspirone","C",21,"H",31,"N",5,"O",2);
row("Compounds",1,"Buckminsterfullerene","C",60,);
row("Compounds",1,"Brucine","C",23,"H",26,"N",2,"O",4);
row("Compounds",1,"Bromotrifluoromethane","C",1,"Br",1,"F",3);
row("Compounds",1,"Bromothymol blue","C",27,"H",28,"Br",2,"O",5);
row("Compounds",1,"Bromophenol blue","C",19,"H",10,"Br",4,"O",5);
row("Compounds",1,"Bromoform","C",1,"H",1,"Br",3);
row("Compounds",1,"Bromocyclohexane","C",6,"H",12,"Br",1);
row("Compounds",1,"Bromocresol purple","C",21,"H",16,"Br",2,"O",5);
row("Compounds",1,"Bromobenzene","C",6,"H",5,"Br",1);
row("Compounds",1,"Bromoacetic acid","C",2,"H",3,"Br",1,"O",2);
row("Compounds",1,"Bromacil","C",9,"H",13,"Br",1,"N",2,"O",2);
row("Compounds",1,"Borneol","C",10,"H",18);
row("Compounds",1,"Biuret","C",2,"H",5,"N",3,"O",2);
row("Compounds",1,"Bisphenol A","C",15,"H",16,"O",2);
row("Compounds",1,"Bismarck brown Y","C",21,"H",24,"N",8);
row("Compounds",1,"Bis(chloromethyl) ether","C",2,"H",4,"Cl",2);
row("Compounds",1,"Biphenyl","C",12,"H",10);
row("Compounds",1,"Biotin (Vitamin H)","C",10,"H",16,"N",2,"O",3);
row("Compounds",1,"Betulin","C",30,"H",50,"O",2);
row("Compounds",1,"Benzylidene acetone","C",10,"H",10);
row("Compounds",1,"Benzyldimethylamine","C",9,"H",13);
row("Compounds",1,"Benzylamine","C",7,"H",9);
row("Compounds",1,"Benzyl chloroformate","C",8,"H",7,"Cl",1,"O",2);
row("Compounds",1,"Benzyl alcohol","C",7,"H",8);
row("Compounds",1,"Benzoylmethylecgonine","C",17,"H",21,"N",1,"O",4);
row("Compounds",1,"Benzoxazole","C",7,"H",5,"N",1,"O",1);
row("Compounds",1,"Benzotriazole","C",6,"H",5,"N",3);
row("Compounds",1,"Benzothiophene","C",8,"H",6);
row("Compounds",1,"Benzothiazole","C",7,"H",5,"NS",1);
row("Compounds",1,"Benzokfluoranthene","C",20,"H",12);
row("Compounds",1,"Benzojfluoranthene","C",20,"H",12);
row("Compounds",1,"Benzoin","C",14,"H",12,"O",2);
row("Compounds",1,"Benzoic acid","C",7,"H",6,"O",2);
row("Compounds",1,"Benzoghiperylene","C",22,"H",12);
row("Compounds",1,"Benzofuran","C",8,"H",6);
row("Compounds",1,"Benzoepyrene","C",20,"H",12);
row("Compounds",1,"Benzoefluoranthene","C",20,"H",12);
row("Compounds",1,"Benzocthiophene","C",8,"H",6);
row("Compounds",1,"benzocphenanthrene","C",18,"H",12);
row("Compounds",1,"Benzoccinnoline","C",12,"H",8,"N",2);
row("Compounds",1,"Benzocaine","C",9,"H",11,"O",2);
row("Compounds",1,"Benzoapyrene","C",20,"H",12);
row("Compounds",1,"Benzoaanthracene","C",18,"H",12);
row("Compounds",1,"Benzisoxazole","C",7,"H",5,"N",1,"O",1);
row("Compounds",1,"Benzisothiazolinone","C",7,"H",5,"N",1,"O",1,"S",1);
row("Compounds",1,"Benzimidazole","C",7,"H",6,"N",2);
row("Compounds",1,"Benzilic acid","C",14,"H",12,"O",3);
row("Compounds",1,"Benzil","C",14,"H",10,"O",2);
row("Compounds",1,"Benzidine","C",12,"H",12,"N",2);
row("Compounds",1,"Benzanthrone","C",17,"H",10);
row("Compounds",1,"Benzamide","C",7,"H",7,"N",1,"O",1);
row("Compounds",1,"Benzaldehyde","C",7,"H",6);
row("Compounds",1,"Benomyl","C",14,"H",18,"N",4,"O",3);
row("Compounds",1,"Behenic acid","C",22,"H",44,"O",2);
row("Compounds",1,"Barbituric acid","C",4,"H",4,"N",2,"O",3);
row("Compounds",1,"Barbital","C",8,"H",12,"N",2,"O",3);
row("Compounds",1,"Bacillomycin","C",45,"H",68,"N",10,"O",15);
row("Compounds",1,"Azure A","C",14,"H",14,"Cl",1,"N",3);
row("Compounds",1,"Azulene","C",10,"H",8);
row("Compounds",1,"Azobenzene","C",12,"H",10,"N",2);
row("Compounds",1,"Azo violet","C",12,"H",9,"N",3,"O",4);
row("Compounds",1,"Azithromycin","C",38,"H",72,"N",2,"O",12);
row("Compounds",1,"Aziridine","C",2,"H",5);
row("Compounds",1,"Azinphos-methyl","C",10,"H",12,"N",3,"O",3,"P",1,"S",2);
row("Compounds",1,"Azelaic acid","C",9,"H",16,"O",4);
row("Compounds",1,"Azathioprine","C",9,"H",7,"N",7,"O",2);
row("Compounds",1,"Avobenzone","C",20,"H",22,"O",3);
row("Compounds",1,"Aureine","C",18,"H",25,"N",1,"O",5);
row("Compounds",1,"Auramine o","C",8,"H",14,"Cl",1,"N",5);
row("Compounds",1,"Atrazine","C",8,"H",14,"Cl",1,"N",5);
row("Compounds",1,"Asphidophytidine","C",17,"H",22,"Cl",1,"N",3);
row("Compounds",1,"Aspartic acid","C",4,"H",7,"N",1,"O",4);
row("Compounds",1,"Aspartame","C",14,"H",18,"N",2,"O",5);
row("Compounds",1,"Asparagusic acid","C",4,"H",6,"O",2,"S",2);
row("Compounds",1,"Asparagine","C",4,"H",8,"N",2,"O",3);
row("Compounds",1,"Ascorbic acid (vitamin C)","C",6,"H",8,"O",6);
row("Compounds",1,"Aroclor","C",12,"H",10,"Cl",1);
row("Compounds",1,"Arginine","C",6,"H",14,"N",4,"O",2);
row("Compounds",1,"Arabinose","C",5,"O",10,"H",5);
row("Compounds",1,"Aprotinin","C",284,"H",432,"N",84,"O",79,"S",7);
row("Compounds",1,"Antipyrine","C",11,"H",12,"N",2);
row("Compounds",1,"Anthrone","C",14,"H",10);
row("Compounds",1,"Anthraquinone","C",14,"H",8,"O",2);
row("Compounds",1,"Anthranilic acid","C",7,"H",7,"N",1,"O",2);
row("Compounds",1,"Anthramine","C",14,"H",11);
row("Compounds",1,"Anthanthrene","C",22,"H",12);
row("Compounds",1,"Anisole","C",6,"H",5,"OC",1,"H",2);
row("Compounds",1,"Anilazine","C",9,"H",5,"Cl",3,"N",4);
row("Compounds",1,"Angelic acid","C",5,"H",8,"O",2);
row("Compounds",1,"Anethole","C",10,"H",12);
row("Compounds",1,"Amyl nitrate","C",5,"H",11,"N",1,"O",3);
row("Compounds",1,"Amphetamine","C",9,"H",13);
row("Compounds",1,"Amobarbital","C",11,"H",18,"N",2,"O",3);
row("Compounds",1,"Amiton","C",10,"H",24,"N",1,"O",3,"P",1,"S",1);
row("Compounds",1,"Amiodarone","C",25,"H",29,"I",2,"N",1,"O",3);
row("Compounds",1,"Aminothiazole","C",3,"H",4,"N",2);
row("Compounds",1,"Aminophylline","C",16,"H",24,"N",10,"O",4);
row("Compounds",1,"Aminoethylpiperazine","C",6,"H",15,"N",3);
row("Compounds",1,"Aminodiacetic acid","C",4,"H",7,"N",1,"O",4);
row("Compounds",1,"Amido black 10b","C",22,"H",14,"N",6,"Na",2,"O",9,"S",2);
row("Compounds",1,"Allylamine","C",3,"H",7);
row("Compounds",1,"Allyl propyl disulfide","C",6,"H",12,"S",2);
row("Compounds",1,"Allantoin","C",4,"H",6,"N",4,"O",3);
row("Compounds",1,"Allantoic acid","C",4,"H",8,"N",4,"O",4);
row("Compounds",1,"Alizarin","C",14,"H",8,"O",4);
row("Compounds",1,"Aliquat 336","C",25,"H",54,"Cl",1);
row("Compounds",1,"Aldrin","C",12,"H",8,"Cl",6);
row("Compounds",1,"Aldosterone","C",21,"H",28,"O",5);
row("Compounds",1,"Alcian blue","C",56,"H",58,"Cl",14,"Cu",1,"N",16,"S",4);
row("Compounds",1,"Alanine","C",3,"H",7,"N",1,"O",2);
row("Compounds",1,"Adrenochrome","C",9,"H",9,"N",1,"O",3);
row("Compounds",1,"Adrenochrome","C",9,"H",9,"N",1,"O",3);
row("Compounds",1,"Adonitol","C",5,"H",12,"O",5);
row("Compounds",1,"Adiponitrile","C",6,"H",8,"N",2);
row("Compounds",1,"Adipic acid","C",6,"H",10,"O",4);
row("Compounds",1,"Adipamide","C",6,"H",12,"N",2,"O",2);
row("Compounds",1,"Adenosine","C",10,"H",13,"N",5,"O",4);
row("Compounds",1,"Adamantane","C",10,"H",16);
row("Compounds",1,"Acyclovir","C",8,"H",11,"N",5,"O",3);
row("Compounds",1,"Acrylonitrile","C",3,"H",3,"N",1);
row("Compounds",1,"Acrylic acid","C",3,"H",4,"O",2);
row("Compounds",1,"Acrylamide","C",3,"H",5,"N",1,"O",1);
row("Compounds",1,"Acrolein","C",17,"H",19,"N",3);
row("Compounds",1,"Acridine","C",13,"H",9,"N",1);
row("Compounds",1,"Acridine orange","C",17,"H",19,"N",3);
row("Compounds",1,"Acetylsalicylic Acid","C",9,"H",8,"O",4);
row("Compounds",1,"Acetylene","C",2,"H",2);
row("Compounds",1,"Acetylcholine","C",7,"H",13,"O",2,"N",1);
row("Compounds",1,"Acetophenone","C",8,"H",8,"O",1);
row("Compounds",1,"Acetonitrile","C",2,"H",3,"N",1);
row("Compounds",1,"Acetone","C",10,"H",11,"Cl",1,"N",4);
row("Compounds",1,"Acetoguanamine","C",3,"H",6,"O",1);
row("Compounds",1,"Acetic acid","C",2,"H",4,"O",2);
row("Compounds",1,"Acetanilide","C",8,"0,",1,"H",9,"N",1);
row("Compounds",1,"Acetamiprid","C",10,"H",11,"Cl",2,"N",4);
row("Compounds",1,"Acetaminosalol","C",15,"H",13,"N",1,"O",4);
row("Compounds",1,"Acetaminophen","C",8,"H",9,"N",1,"O",2);
row("Compounds",1,"Acetamideonium","C",2,"H",5,"O",1,"N",1);
row("Compounds",1,"Acetaldehyde","C",2,"H",4,"O",1);
row("Compounds",1,"Acepromazine","C",19,"H",22,"N",1,"O",2);
row("Compounds",1,"Acenaphthylene","C",12,"H",8);
row("Compounds",1,"Acenaphthoquinone","C",12,"H",6,"O",2);
row("Compounds",1,"Acenaphthene","C",12,"H",10);
row("Compounds",1,"Abietic acid","C",20,"H",30,"O",10);
row("Compounds",1,"a-Terpineol","C",10,"H",18);
row("Compounds",1,"9-Fluorenone","C",13,"H",8);
row("Compounds",1,"5-Hydroxytryptamine","C",10,"H",12,"N",2);
row("Compounds",1,"5-Hydroxymethylcytosine","C",5,"H",7,"N",3,"O",2);
row("Compounds",1,"5-Amino-2-hydroxybenzoic acid","C",7,"H",7,"N",1,"O",3);
row("Compounds",1,"4-Picoline","C",6,"H",7);
row("Compounds",1,"Phenyl-piperidinyl cyclohexanol","C",17,"H",25,"N",1,"O",1);
row("Compounds",1,"4-Methylbenzoic acid","C",8,"H",8,"O",2);
row("Compounds",1,"Anisaldehyde","C",8,"H",8,"O",2);
row("Compounds",1,"4-Chloroaniline","C",6,"H",6,"Cl",1);
row("Compounds",1,"3 3'-Diaminobenzidine","C",12,"H",14,"N",4);
row("Compounds",1,"2-Pyridone","C",5,"H",5,"N",1,"O",1);
row("Compounds",1,"2-Propanone","C",3,"H",6);
row("Compounds",1,"2-Naphthylamine","C",10,"H",9);
row("Compounds",1,"2-Methylpropene (isobutylene)","C",4,"H",8);
row("Compounds",1,"o-Toluic acid","C",8,"H",8,"O",2);
row("Compounds",1,"2-Mercaptoethanol","C",2,"H",6,"OS",1);
row("Compounds",1,"2-Ethyl-1-hexanol","C",8,"H",18);
row("Compounds",1,"2-Chlorobenzoic acid","C",7,"H",5,"Cl",1,"O",2);
row("Compounds",1,"Tert butyl chloride","C",4,"H",9,"Cl",1);
row("Compounds",1,"2-Butyne-1 4-diol","C",4,"H",6,"O",2);
row("Compounds",1,"2-Butoxyethanol","C",6,"H",14,"O",2);
row("Compounds",1,"2-Bromopropane","C",3,"H",7,"Br",1);
row("Compounds",1,"2-Bromo-1-chloropropane","C",3,"H",6,"Br",1,"Cl",1);
row("Compounds",1,"2 6-Lutidine","C",7,"H",9);
row("Compounds",1,"2 6-Di-tert-butylpyridine","C",13,"H",21);
row("Compounds",1,"2 6-Di-tert-butylphenol","C",11,"H",13);
row("Compounds",1,"2 6-Di-tert-butyl-4-methylphenol","C",15,"H",24);
row("Compounds",1,"2 4-Dichlorophenoxyacetic acid","C",8,"H",6,"Cl",2,"O",3);
row("Compounds",1,"2 4 6-Trichlorophenol","C",6,"H",3,"Cl",1,"P",3);
row("Compounds",1,"2 4 6-Trichloroanisole","C",7,"H",5,"Cl",1,"F",3);
row("Compounds",1,"2 2'-Bipyridine(2 2'-Bipyridyl)","C",10,"H",8,"N",2);
row("Compounds",1,"2 2 4-Trimethylpentane","C",8,"H",18);
row("Compounds",1,"2 2 2-Trifluoroethanol","C",2,"H",3,"F",3);
row("Compounds",1,"18-Crown-6","C",12,"H",24,"O",6);
row("Compounds",1,"1 8-Bismuth Proton-sponge","C",14,"H",18,"N",2);
row("Compounds",1,"1 4-Dimethylbenzene (p-Xylene)","C",8,"H",10);
row("Compounds",1,"1 4-Cyclohexadiene","C",6,"H",8);
row("Compounds",1,"1 3-Dimethylbenzene (m-Xylene)","C",8,"H",10);
row("Compounds",1,"1 3-Cyclohexadiene","C",6,"H",8);
row("Compounds",1,"1 3-Butadiene","C",4,"H",6);
row("Compounds",1,"1 2-Dimethylbenzene (o-Xylene)","C",8,"H",10);
row("Compounds",1,"1 2-Dichloroethane","C",2,"H",4,"Cl",2);
row("Compounds",1,"1 2-Dibromoethane","C",2,"H",4,"Br",1,"O",2);
row("Compounds",1,"1 1 1-Trifluoroethane","C",2,"H",3,"F",3);
row("Compounds",1,"1 1 1-Trichloroethane","C",2,"H",3,"Cl",1,"O",3);
row("Compounds",0,"Zirconium(IV) oxide","Zr",1,"O",2);
row("Compounds",0,"Zirconium tungstate","Zr",1,"W",2,"O",8);
row("Compounds",0,"Zirconium tetrahydroxide","H",4,"O",4,"Zr",1);
row("Compounds",0,"Zirconium orthosilicate","Zr",1,"Si",1,"O",4);
row("Compounds",0,"Zirconium nitride","Zr",1,"N",1);
row("Compounds",0,"Zirconium hydroxide","Zr",1,"O",4,"H",4);
row("Compounds",0,"Zirconium carbide","Zr",1,"C",1);
row("Compounds",0,"Zirconia hydrate","Zr",1,"O",3,"H",2);
row("Compounds",0,"Zinc telluride","Zn",1,"Te",1);
row("Compounds",0,"Zinc sulfide","Zn",1,"S",1);
row("Compounds",0,"Zinc sulfate","Zn",1,"S",1,"O",4);
row("Compounds",0,"Zinc selenide","Zn",1,"Se",1);
row("Compounds",0,"Zinc oxide","Zn",1,"O",1);
row("Compounds",0,"Zinc cyanide","Zn",1,"C",2,"N",2);
row("Compounds",0,"Zinc carbonate","Zn",1,"C",1,"O",3);
row("Compounds",0,"Yttrium(III) sulfide","Y",2,"S",3);
row("Compounds",0,"Yttrium(III) oxide","Y",2,"O",3);
row("Compounds",0,"Yttrium(III) arsenide","Y",1,"As",1);
row("Compounds",0,"Yttrium(III) antimonide","Y",1,"Sb",1);
row("Compounds",0,"Yttrium zinc","Y",1,"Zn",1);
row("Compounds",0,"Yttrium silver","Y",1,"Ag",1);
row("Compounds",0,"Yttrium rhodium","Y",1,"Rh",1);
row("Compounds",0,"Yttrium magnesium","Y",1,"Mg",1);
row("Compounds",0,"Yttrium iron garnet","Y",3,"Fe",5,"O",12);
row("Compounds",0,"Yttrium iridium","Y",1,"Ir",1);
row("Compounds",0,"Yttrium gold","Y",1,"Au",1);
row("Compounds",0,"Yttrium copper","Y",1,"Cu",1);
row("Compounds",0,"Yttrium cadmium","Y",1,"Cd",1);
row("Compounds",0,"Yttrium barium copper oxide","Y",1,"Ba",2,"Cu",3,"O",7);
row("Compounds",0,"Yttrium aluminium garnet","Y",3,"Al",5,"O",12);
row("Compounds",0,"Ytterbium(III) oxide","Yb",2,"O",3);
row("Compounds",0,"Xenon tetroxide","Xe",1,"O",4);
row("Compounds",0,"Xenon tetrafluoride","Xe",1,"F",4);
row("Compounds",0,"Xenon hexafluoroplatinate","Xe",1,"Pt",1,"F",6);
row("Compounds",0,"Xenon difluoride","Xe",1,"F",2);
row("Compounds",0,"Xenic acid","H",2,"Xe",1,"O",4);
row("Compounds",0,"Water","H",2,"O",1);
row("Compounds",0,"Vanadium(V) oxide","V",2,"O",5);
row("Compounds",0,"Vanadium(IV) sulfate","V",1,"O",5,"S",1);
row("Compounds",0,"Vanadium(IV) oxide","V",1,"O",2);
row("Compounds",0,"Vanadium(III) oxide","V",2,"O",3);
row("Compounds",0,"Vanadium(III) nitride","V",1,"N",1);
row("Compounds",0,"Vanadium(II) oxide","V",1,"O",1);
row("Compounds",0,"Vanadium oxytrichloride","V",1,"O",1,"Cl",3);
row("Compounds",0,"Vanadium carbide – VC","V",1,"C",1);
row("Compounds",0,"Uranyl nitrate","U",1,"O",8,"N",2,"O",3);
row("Compounds",0,"Uranium hexafluoride","U",1,"F",6);
row("Compounds",0,"Tungstic acid","H",2,"W",1,"O",4);
row("Compounds",0,"Tungsten hexacarbonyl","W",1,"C",6,"O",6);
row("Compounds",0,"Tungsten carbide","W",1,"C",1);
row("Compounds",0,"Triuranium octaoxide","U",3,"O",8);
row("Compounds",0,"Trisodium phosphate","Na",3,"P",1,"O",4);
row("Compounds",0,"Tripotassium phosphate","K",3,"P",1,"O",4);
row("Compounds",0,"Trioxidane","H",2,"O",3);
row("Compounds",0,"Trimethylphosphine","C",3,"H",9,"P",1);
row("Compounds",0,"Trifluoromethylisocyanide","C",2,"N",1,"F",3);
row("Compounds",0,"Trifluoromethanesulfonic acid","C",1,"F",3,"S",1,"O",3,"H",1);
row("Compounds",0,"Titanium nitride","Ti",1,"N",1);
row("Compounds",0,"Titanium(IV) oxide","Ti",1,"O",2);
row("Compounds",0,"Titanium dioxide","Ti",1,"O",2);
row("Compounds",0,"Titanium carbide","Ti",1,"C",1);
row("Compounds",0,"Titanium boride","Ti",1,"B",2);
row("Compounds",0,"Thortveitite","Sc",2,"Y",2,"Si",2,"O",7);
row("Compounds",0,"Thorium dioxide","Th",1,"O",2);
row("Compounds",0,"Thiophosphoryl chloride","Cl",3,"P",1,"S",1);
row("Compounds",0,"Thiophosgene","C",1,"S",1,"Cl",2);
row("Compounds",0,"Thallium(III) sulfate","Tl",3,"S",1,"O",4);
row("Compounds",0,"Thallium(III) oxide","Tl",2,"O",3);
row("Compounds",0,"Thallium(I) fluoride","Tl",1,"F",1);
row("Compounds",0,"Thallium(I) carbonate","Tl",2,"C",1,"O",3);
row("Compounds",0,"Tetrasulfur tetranitride","S",4,"N",4);
row("Compounds",0,"Tetramminecopper(II) sulfate","Cu",1,"N",4,"H",12,"S",1,"O",4);
row("Compounds",0,"Tetrafluorohydrazine","N",2,"F",4);
row("Compounds",0,"Tetrachloroauric acid","Au",1,"Cl",3);
row("Compounds",0,"Terbium(III) chloride","Tb",1,"Cl",3);
row("Compounds",0,"Tellurous acid","H",2,"Te",1,"O",3);
row("Compounds",0,"Tellurium tetrachloride","Te",1,"Cl",4);
row("Compounds",0,"Tellurium dioxide","Te",1,"O",2);
row("Compounds",0,"Telluric acid","H",6,"Te",1,"O",6);
row("Compounds",0,"Tantalum(V) oxide","Ta",2,"O",5);
row("Compounds",0,"Tantalum carbide","Ta",1,"C",1);
row("Compounds",0,"Sulfurous acid","H",2,"S",1,"O",3);
row("Compounds",0,"Sulfuric acid","H",2,"S",1,"O",4);
row("Compounds",0,"Sulfur dioxide","S",1,"O",2);
row("Compounds",0,"Sulfane","H",2,"S",1);
row("Compounds",0,"Sulfamic acid","H",3,"N",1,"O",3,"S",1);
row("Compounds",0,"Strontium titanate","Sr",1,"Ti",1,"O",3);
row("Compounds",0,"Strontium nitrate","Sr",1,"N",2,"O",6);
row("Compounds",0,"Stibine","Sb",1,"H",3);
row("Compounds",0,"Sodium(III) phosphate","Na",3,"P",1,"O",4);
row("Compounds",0,"Sodium tellurite","Na",2,"Te",1,"O",3);
row("Compounds",0,"Sodium sulfite","Na",2,"S",1,"O",3);
row("Compounds",0,"Sodium sulfide","Na",2,"S",1);
row("Compounds",0,"Sodium sulfate","Na",2,"S",1,"O",4);
row("Compounds",0,"Sodium silicate","Na",2,"Si",1,"O",3);
row("Compounds",0,"Sodium persulfate","Na",2,"S",2,"O",8);
row("Compounds",0,"Sodium percarbonate","Na",2,"C",2,"O",9,"H",6);
row("Compounds",0,"Sodium nitrite","Na",1,"N",1,"O",2);
row("Compounds",0,"Sodium nitrate","Na",1,"N",1,"O",3);
row("Compounds",0,"Sodium monofluorophosphate (MFP)","Na",2,"P",1,"F",1,"O",3);
row("Compounds",0,"Sodium hydroxide","Na",1,"O",1,"H",1);
row("Compounds",0,"Sodium hydrosulfide","Na",1,"S",1,"H",1);
row("Compounds",0,"Sodium hydrogen carbonate","Na",1,"H",1,"C",1,"O",3);
row("Compounds",0,"Sodium hydride","Na",1,"H",1);
row("Compounds",0,"Sodium ferrocyanide","Na",4,"Fe",1,"C",6,"N",6);
row("Compounds",0,"Sodium cyanide","Na",1,"C",1,"N",1);
row("Compounds",0,"Sodium chlorate","Na",1,"Cl",1,"O",3);
row("Compounds",0,"Sodium carbonate","Na",2,"C",1,"O",3);
row("Compounds",0,"Sodium bromate","Na",1,"Br",1,"O",3);
row("Compounds",0,"Sodium borohydride","Na",1,"B",1,"H",4);
row("Compounds",0,"Sodamide","Na",1,"N",1,"H",2);
row("Compounds",0,"Soda lime","Ca",1,"O",5,"Na",1,"K",1,"H",6);
row("Compounds",0,"Silver sulfide","Ag",2,"S",1);
row("Compounds",0,"Silver nitrate","Ag",1,"N",1,"O",3);
row("Compounds",0,"Silicon dioxide","Si",1,"O",2);
row("Compounds",0,"Silicon carbide (Carborundum)","Si",1,"C",1);
row("Compounds",0,"Silicofluoric acid","H",2,"Si",1,"F",6);
row("Compounds",0,"Silicochloroform","Cl",3,"H",1,"Si",1);
row("Compounds",0,"Silicic acid","Si",1,"O",1,"H",4);
row("Compounds",0,"Silica gel","Si",1,"O",2,"H",2,"O",1);
row("Compounds",0,"Silane","Si",1,"H",4);
row("Compounds",0,"Selenium trioxide","Se",1,"O",3);
row("Compounds",0,"Selenium dioxide","Se",1,"O",2);
row("Compounds",0,"Selenious acid","H",2,"Se",1,"O",3);
row("Compounds",0,"Selenic acid","H",2,"Se",1,"O",4);
row("Compounds",0,"Scandium(III) triflate","Sc",1,"O",9,"S",3,"C",3,"F",9);
row("Compounds",0,"Scandium(III) oxide","Sc",2,"O",3);
row("Compounds",0,"Scandium(III) nitrate","Sc",1,"N",3,"O",9);
row("Compounds",0,"Ruthenium(VIII) oxide","Ru",1,"O",4);
row("Compounds",0,"Rubidium telluride","Rb",2,"Te",1);
row("Compounds",0,"Rubidium oxide","Rb",2,"O",1);
row("Compounds",0,"Rubidium nitrate","Rb",1,"N",1,"O",3);
row("Compounds",0,"Rubidium hydroxide","Rb",1,"O",1,"H",1);
row("Compounds",0,"Quartz","Si",1,"O",2);
row("Compounds",0,"Pyrosulfuric acid","H",2,"S",2,"O",7);
row("Compounds",0,"Iron hexacyanoferrate","Fe",7,"C",18,"N",18);
row("Compounds",0,"Protonated molecular hydrogen","H",3,);
row("Compounds",0,"Potassium vanadate","K",1,"V",1,"O",3);
row("Compounds",0,"Potassium titanyl phosphate","K",1,"Ti",1,"O",5,"P",1);
row("Compounds",0,"Potassium sulfide","K",2,"S",1);
row("Compounds",0,"Potassium sulfate","K",2,"S",1,"O",4);
row("Compounds",0,"Potassium permanganate","K",1,"Mn",1,"O",4);
row("Compounds",0,"Potassium perchlorate","K",1,"Cl",1,"O",4);
row("Compounds",0,"Potassium perbromate","K",1,"Br",1,"O",4);
row("Compounds",0,"Potassium nitrate","K",1,"N",1,"O",3);
row("Compounds",0,"Potassium monopersulfate","K",5,"S",4,"O",18);
row("Compounds",0,"Potassium hydroxide","K",1,"O",1,"H",1);
row("Compounds",0,"Potassium hydrogencarbonate","K",1,"H",1,"C",1,"O",3);
row("Compounds",0,"Potassium hydrogen fluoride","H",1,"F",2,"K",1);
row("Compounds",0,"Potassium ferrioxalate","K",3,"Fe",3,"C",6,"O",12);
row("Compounds",0,"Potassium chlorate","K",1,"Cl",1,"O",3);
row("Compounds",0,"Potassium borate","K",2,"B",4,"O",11,"H",8);
row("Compounds",0,"Potassium Aluminium Fluoride","K",1,"Al",1,"F",4);
row("Compounds",0,"Potash Alum","K",2,"S",2,"O",32,"H",48,"Al",2);
row("Compounds",0,"Plutonium(III) chloride","Pu",1,"Cl",3);
row("Compounds",0,"Plutonium dioxide","Pu",1,"O",2,);
row("Compounds",0,"Platinum(IV) chloride","Pt",1,"Cl",4);
row("Compounds",0,"Platinum(II) chloride","Pt",1,"Cl",2);
row("Compounds",0,"Phosphotungstic acid","H",3,"P",1,"W",12,"O",40);
row("Compounds",0,"Phosphorus triiodide","P",1,"I",3);
row("Compounds",0,"Phosphorus trifluoride","P",1,"F",3);
row("Compounds",0,"Phosphorus trichloride","P",1,"Cl",3);
row("Compounds",0,"Phosphorus tribromide","P",1,"Br",3);
row("Compounds",0,"Phosphorus sesquisulfide","P",4,"S",3);
row("Compounds",0,"Phosphorus pentoxide","P",2,"O",5);
row("Compounds",0,"Phosphorus pentasulfide","P",4,"S",10);
row("Compounds",0,"Phosphorus pentafluoride","P",1,"F",5);
row("Compounds",0,"Phosphorus pentabromide","P",1,"Br",5);
row("Compounds",0,"Phosphorous acid","H",3,"P",1,"O",3,);
row("Compounds",0,"Phosphoric acid","H",3,"P",1,"O",4);
row("Compounds",0,"Phosphomolybdic acid","H",1,"Mo",1,"Ni",1,"O",6,"P",1);
row("Compounds",0,"Phosphite","H",1,"P",1,"O",32);
row("Compounds",0,"Phosphine","P",1,"H",3);
row("Compounds",0,"Phosgene","C",1,"O",1,"Cl",2);
row("Compounds",0,"Phenylphosphine","C",6,"H",7,"P",1);
row("Compounds",0,"Phenylarsine oxide","C",6,"H",5,"As",1,"O",1);
row("Compounds",0,"Perxenic acid","H",4,"Xe",1,"O",6);
row("Compounds",0,"Persulfuric acid (Caro's acid)","H",2,"S",1,"O",5);
row("Compounds",0,"Perchloric acid","H",1,"Cl",1,"O",4);
row("Compounds",0,"Pentasulfide antimony","Sb",2,"S",5);
row("Compounds",0,"Pentaborane","B",5,"H",9);
row("Compounds",0,"Palladium(II) nitrate","Pd",1,"N",2,"O",6);
row("Compounds",0,"Ozone","O",3,);
row("Compounds",0,"Oxygen","O",2,);
row("Compounds",0,"Oxybis (tributyltin)","C",24,"H",54,"O",1,"Sn",2);
row("Compounds",0,"Osmium trioxide","Os",1,"O",3);
row("Compounds",0,"Osmium tetroxide","Os",1,"O",4);
row("Compounds",0,"Nitrosylsulfuric acid","N",1,"O",1,"H",1,"S",1,"O",4);
row("Compounds",0,"Nitrogen","N",2,);
row("Compounds",0,"Nitrogen monoxide","N",1,"O",1);
row("Compounds",0,"Nitrogen dioxide","N",1,"O",2);
row("Compounds",0,"Nitric acid","H",1,"N",1,"O",3);
row("Compounds",0,"Niobium pentachloride","Nb",1,"Cl",5);
row("Compounds",0,"Niobium oxychloride","Nb",1,"O",1,"Cl",3);
row("Compounds",0,"Nickel(II) oxide","Ni",1,"O",1);
row("Compounds",0,"Nickel(II) nitrate","Ni",1,"N",2,"O",6);
row("Compounds",0,"Nickel(II) hydroxide","Ni",1,"O",2,"H",2);
row("Compounds",0,"Nickel(II) carbonate","Ni",1,"C",1,"O",3);
row("Compounds",0,"Nessler's reagent","K",2,"Hg",1,"I",4);
row("Compounds",0,"Molybdic acid","H",2,"Mo",1,"O",4);
row("Compounds",0,"Molybdenum trioxide","Mo",1,"O",3);
row("Compounds",0,"Molybdenum hexacarbonyl","C",6,"O",6,"Mo",1);
row("Compounds",0,"Molybdenum disulfide","Mo",1,"S",2);
row("Compounds",0,"Molybdate orange","Mo",1,"O",3,"Pb",1,"Cl",2,"S",7);
row("Compounds",0,"Methane","C",1,"H",4);
row("Compounds",0,"Metaphosphoric acid","H",1,"P",1,"O",3);
row("Compounds",0,"Mercury(II) telluride","Hg",1,"Te",1);
row("Compounds",0,"Mercury(II) sulfide","Hg",1,"S",1);
row("Compounds",0,"Mercury(II) sulfate","Hg",1,"S",1,"O",4);
row("Compounds",0,"Mercury(II) selenide","Hg",1,"Se",1);
row("Compounds",0,"Mercury(I) sulfate","Hg",2,"S",1,"O",4);
row("Compounds",0,"Mercury fulminate","Hg",1,"O",2,"N",2,"C",2);
row("Compounds",0,"Manganese dioxide","Mn",1,"O",2);
row("Compounds",0,"Manganese(II) sulfate monohydrate","Mn",1,"S",1,"O",5,"H",2);
row("Compounds",0,"Manganese(II) phosphate","Mn",3,"P",2,"O",8);
row("Compounds",0,"Magnesium sulfate","Mg",1,"S",1,"O",4);
row("Compounds",0,"Magnesium phosphate","Mg",3,"P",2,"O",8);
row("Compounds",0,"Magnesium oxide","Mg",1,"O",1);
row("Compounds",0,"Magnesium carbonate","Mg",1,"C",1,"O",3);
row("Compounds",0,"Magnesium antimonide","Mg",1,"Sb",1);
row("Compounds",0,"Lithium sulfate","Li",2,"S",1,"O",4);
row("Compounds",0,"Lithium nitrate","Li",1,"N",1,"O",3);
row("Compounds",0,"Lithium iodide","Li",1,"I",1);
row("Compounds",0,"Lithium hydroxide","Li",1,"O",1,"H",1);
row("Compounds",0,"Lithium hydride","Li",1,"H",1);
row("Compounds",0,"Lithium carbonate (Lithium salt)","Li",2,"C",1,"O",3);
row("Compounds",0,"Lithium aluminium hydride","Li",1,"Al",1,"H",4);
row("Compounds",0,"Lead(IV) oxide","Pb",1,"O",2);
row("Compounds",0,"Lead(II) telluride","Pb",1,"Te",1);
row("Compounds",0,"Lead(II) sulfide","Pb",1,"S",1);
row("Compounds",0,"Lead(II) sulfate","Pb",1,"S",1,"O",4);
row("Compounds",0,"Lead(II) selenide","Pb",1,"Se",1);
row("Compounds",0,"Lead(II) phosphate","Pb",3,"P",2,"O",8);
row("Compounds",0,"Lead(II) oxide","Pb",1,"O",1);
row("Compounds",0,"Lead(II) nitrate","Pb",1,"N",2,"O",6);
row("Compounds",0,"Lead(II) iodide","Pb",1,"I",2);
row("Compounds",0,"Lead(II) carbonate","Pb",1,"C",1,"O",3);
row("Compounds",0,"Lead zirconate titanate","Pb",1,"Ti",1,"Zr",1,"O",3);
row("Compounds",0,"Lanthanum zinc","La",1,"Zn",1);
row("Compounds",0,"Lanthanum tallium","La",1,"Tl",1);
row("Compounds",0,"Lanthanum silver","La",1,"Ag",1);
row("Compounds",0,"Lanthanum mercury","La",1,"Hg",1);
row("Compounds",0,"Lanthanum magnesium","La",1,"Mg",1);
row("Compounds",0,"Lanthanum carbonate","La",2,"C",3,"O",9);
row("Compounds",0,"Lanthanum cadmium","La",1,"Cd",1);
row("Compounds",0,"Lanthanum aluminium","La",1,"Al",1);
row("Compounds",0,"Krypton difluoride","Kr",1,"F",2);
row("Compounds",0,"Iron-sulfur cluster","Fe",1,"S",1);
row("Compounds",0,"Iron(III) thiocyanate","Fe",3,"C",8,"N",8,"S",8);
row("Compounds",0,"Iron(III) oxide","Fe",2,"O",3);
row("Compounds",0,"Iron(III) nitrate","Fe",1,"N",3,"O",18,"H",18);
row("Compounds",0,"Iron(II) oxide","Fe",1,"O",1);
row("Compounds",0,"Iron(II III) oxide","Fe",3,"O",4);
row("Compounds",0,"Iron Oxide","Fe",2,);
row("Compounds",0,"Iodic acid","H",1,"I",1,"O",3);
row("Compounds",0,"Indium phosphide","In",1,"P",1);
row("Compounds",0,"Indium nitride","In",1,"N",1);
row("Compounds",0,"Indium arsenide","In",1,"As",1);
row("Compounds",0,"Indium antimonide","In",1,"Sb",1);
row("Compounds",0,"Hypophosphorous acid","H",3,"P",1,"O",2);
row("Compounds",0,"Hypochlorous acid","H",1,"Cl",1,"O",1);
row("Compounds",0,"Hydroxylamine","N",1,"H",3,"O",1);
row("Compounds",0,"Hydroiodic acid","H",1,"I",1);
row("Compounds",0,"Hydrogen telluride","H",2,"Te",1);
row("Compounds",0,"Hydrogen sulfide","H",2,"S",1);
row("Compounds",0,"Hydrogen selenide","H",2,"Se",1);
row("Compounds",0,"Hydrogen peroxide","H",2,"O",2);
row("Compounds",0,"Hydrochloric acid","H",1,"Cl",1);
row("Compounds",0,"Hydrobromic acid","H",1,"Br",1);
row("Compounds",0,"Hydrazoic acid","H",1,"N",3);
row("Compounds",0,"Hydrazine","N",2,"H",4);
row("Compounds",0,"Hexadecacarbonylhexarhodium","Rh",6,"C",1,"O",16);
row("Compounds",0,"Gold(III) sulfide","Au",2,"S",3);
row("Compounds",0,"Gold(III) selenide","Au",2,"Se",3);
row("Compounds",0,"Gold(III) selenide","Au",1,"Se",1);
row("Compounds",0,"Gold(III) oxide","Au",2,"O",3);
row("Compounds",0,"Gold(I) sulfide","Au",2,"S",1);
row("Compounds",0,"Gold ditelluride","Au",1,"Te",2);
row("Compounds",0,"Germanium(IV) sulfide","Ge",1,"S",2);
row("Compounds",0,"Germanium(IV) selenide","Ge",1,"Se",2);
row("Compounds",0,"Germanium(IV) oxide","Ge",1,"O",2);
row("Compounds",0,"Germanium(IV) hydride (Germane)","Ge",1,"H",4);
row("Compounds",0,"Germanium(IV) fluoride","Ge",1,"F",4);
row("Compounds",0,"Germanium(III) hydride","Ge",1,"H",6);
row("Compounds",0,"Germanium(II) sulfide","Ge",1,"S",1);
row("Compounds",0,"Germanium(II) selenide","Ge",1,"Se",1);
row("Compounds",0,"Germanium(II) oxide","Ge",1,"O",1);
row("Compounds",0,"Germanium(II) fluoride","Ge",1,"F",2);
row("Compounds",0,"Germanium telluride","Ge",1,"Te",1);
row("Compounds",0,"Germanium (IV) nitride","Ge",3,"N",4);
row("Compounds",0,"Gallium trichloride","Ga",1,"Cl",3);
row("Compounds",0,"Gallium phosphide","Ga",1,"P",1);
row("Compounds",0,"Gallium nitride","Ga",1,"N",1);
row("Compounds",0,"Gallium arsenide","Ga",1,"As",1);
row("Compounds",0,"Gallium antimonide","Ga",1,"Sb",3);
row("Compounds",0,"Gadolinium(III) oxide","Gd",2,"O",3);
row("Compounds",0,"Gadolinium(III) chloride","Gd",1,"Cl",3);
row("Compounds",0,"Fluorosulfuric acid","F",1,"S",1,"O",3,"H",1);
row("Compounds",0,"Erbium-silver","Er",1,"Ag",1);
row("Compounds",0,"Erbium-Iridium","Er",1,"Ir",1);
row("Compounds",0,"Erbium-gold","Er",1,"Au",1);
row("Compounds",0,"Erbium-copper","Eu",1,"Cu",1);
row("Compounds",0,"Disilane","Si",2,"H",6);
row("Compounds",0,"Dinitrogen pentoxide","N",2,"O",5);
row("Compounds",0,"Digallane","Ga",2,"H",6);
row("Compounds",0,"Dichlorosilane","Si",1,"H",2,"Cl",2);
row("Compounds",0,"Diborane","B",2,"B",6);
row("Compounds",0,"Di-Ammonium Phosphate","N",2,"H",9,"P",1,"O",4);
row("Compounds",0,"Decaborane","B",10,"H",14);
row("Compounds",0,"Cyanogen","C",2,"N",2);
row("Compounds",0,"Copper(II) sulfide","Cu",1,"S",1);
row("Compounds",0,"Copper(II) sulfate","Cu",1,"S",1,"O",4);
row("Compounds",0,"Copper(II) oxide","Cu",1,"O",1);
row("Compounds",0,"Copper(II) nitrate","Cu",1,"N",2,"O",6);
row("Compounds",0,"Copper(II) hydroxide","Cu",1,"O",2,"H",2);
row("Compounds",0,"Copper(II) carbonate","Cu",1,"C",1,"O",3);
row("Compounds",0,"Copper(I) sulfide","Cu",2,"S",1);
row("Compounds",0,"Copper(I) oxide","Cu",2,"O",1);
row("Compounds",0,"Columbite","Fe",2,"Nb",2,"O",6);
row("Compounds",0,"Cobalt(II) sulfate","Co",1,"S",1,"O",4);
row("Compounds",0,"Cobalt(II) carbonate","Co",1,"C",1,"O",3);
row("Compounds",0,"Cis-platinum chloride diammine","Pt",1,"Cl",2,"N",2,"H",6);
row("Compounds",0,"Chromium(IV) oxide","Cr",1,"O",2);
row("Compounds",0,"Chromium(III) oxide","Cr",2,"O",3);
row("Compounds",0,"Chromium trioxide (Chromic acid)","Cr",1,"O",3);
row("Compounds",0,"Chromic acid","Cr",1,"O",3);
row("Compounds",0,"Chrome-alum","K",2,"S",1,"O",4,"Cr",2,"H",2,"O",1);
row("Compounds",0,"Cerium(IV) sulfate","Ce",1,"S",2,"O",8);
row("Compounds",0,"Cerium zinc","Ce",1,"Zn",1);
row("Compounds",0,"Cerium thallium","Ce",1,"Tl",1);
row("Compounds",0,"Cerium silver","Ce",1,"Ag",1);
row("Compounds",0,"Cerium mercury","Ce",1,"Hg",1);
row("Compounds",0,"Cerium magnesium","Ce",1,"Mg",1);
row("Compounds",0,"Cerium cadmium","Ce",1,"Cd",1);
row("Compounds",0,"Cerium aluminium","Ce",1,"Al",1);
row("Compounds",0,"Carboplatin","H",5,"N",2,"O",4,"Pt",1);
row("Compounds",0,"Carbonyl sulfide","C",1,"O",1,"S",1);
row("Compounds",0,"Carbonyl fluoride","C",1,"O",1,"F",2);
row("Compounds",0,"Carbonic acid","H",2,"C",1,"O",3);
row("Compounds",0,"Carbon tetraiodide","C",1,"I",4);
row("Compounds",0,"Carbon tetrachloride","C",1,"Cl",4);
row("Compounds",0,"Carbon tetrabromide","C",1,"Br",4);
row("Compounds",0,"Carbon monoxide","C",1,"O",1);
row("Compounds",0,"Carbon disulfide","C",1,"S",2);
row("Compounds",0,"Carbon dioxide","C",1,"O",2);
row("Compounds",0,"Calcium sulfate (Gypsum)","Ca",1,"S",1,"O",4);
row("Compounds",0,"Calcium hydroxide","Ca",1,"O",2,"H",2);
row("Compounds",0,"Calcium hydride","Ca",1,"H",2);
row("Compounds",0,"Calcium cyanamide","Ca",1,"C",1,"N",2);
row("Compounds",0,"Calcium chromate","Ca",1,"Cr",1,"O",4);
row("Compounds",0,"Calcium chlorate","Ca",1,"Cl",2,"O",6);
row("Compounds",0,"Calcium carbide","Ca",1,"C",2);
row("Compounds",0,"Caesium chromate","Cs",2,"Cr",1,"O",4);
row("Compounds",0,"Caesium carbonate","Cs",2,"C",1,"O",3);
row("Compounds",0,"Caesium bicarbonate","Cs",1,"H",1,"C",1,"O",3);
row("Compounds",0,"Cadmium telluride","Cd",1,"Te",1);
row("Compounds",0,"Cadmium sulfate","Cd",1,"S",1,"O",4);
row("Compounds",0,"Cadmium selenide","Cd",1,"Se",1);
row("Compounds",0,"Cadmium nitrate","Cd",1,"N",2,"O",6);
row("Compounds",0,"Cadmium iodide","Cd",1,"I",2);
row("Compounds",0,"Cadmium arsenide","Cd",3,"As",2);
row("Compounds",0,"Cacodylic acid","C",2,"H",7,"As",1,"O",2);
row("Compounds",0,"Bromine trifluoride","Br",1,"F",3);
row("Compounds",0,"Bromine pentafluoride","Br",1,"F",5);
row("Compounds",0,"Boron suboxide","B",6,"O",1);
row("Compounds",0,"Boron oxide","B",2,"O",3);
row("Compounds",0,"Boron nitride","B",1,"N",1);
row("Compounds",0,"Boron carbide","B",4,"C",1);
row("Compounds",0,"Boric acid","H",3,"B",1,"O",3);
row("Compounds",0,"Borax","Na",2,"B",4,"H",20,"O",17);
row("Compounds",0,"Borane","B",1,"H",3);
row("Compounds",0,"Bismuth(III) telluride","Bi",2,"Te",3);
row("Compounds",0,"Bismuth(III) oxide","Bi",2,"O",3);
row("Compounds",0,"Beryllium telluride","Be",1,"Te",1);
row("Compounds",0,"Beryllium sulfite","Be",1,"S",1,"O",3);
row("Compounds",0,"Beryllium sulfate","Be",1,"S",1,"O",4);
row("Compounds",0,"Beryllium oxide","Be",1,"O",1);
row("Compounds",0,"Beryllium nitride","Be",3,"N",2);
row("Compounds",0,"Beryllium nitrate","Be",1,"N",2,"O",6);
row("Compounds",0,"Beryllium iodide","Be",1,"I",2);
row("Compounds",0,"Beryllium hydroxide","Be",1,"O",2,"H",2);
row("Compounds",0,"Beryllium hydride","Be",1,"H",2);
row("Compounds",0,"Beryllium carbonate","Be",1,"C",1,"O",3);
row("Compounds",0,"Beryllium borohydride","Be",1,"B",2,"H",8);
row("Compounds",0,"Barium titanate","Ba",1,"Ti",1,"O",3);
row("Compounds",0,"Barium sulfate","Ba",1,"S",1,"O",4);
row("Compounds",0,"Barium nitrate","Ba",1,"N",2,"O",6);
row("Compounds",0,"Barium iodide","Ba",1,"I",2);
row("Compounds",0,"Barium hydroxide","Ba",1,"O",2,"H",2);
row("Compounds",0,"Barium chromate","Ba",1,"Cr",1,"O",4);
row("Compounds",0,"Baking soda","Na",1,"H",1,"C",1,"O",3);
row("Compounds",0,"Arsine","As",1,"H",3);
row("Compounds",0,"Arsenous acid","As",1,"O",3,"H",3);
row("Compounds",0,"Arsenic trioxide","As",2,"O",3);
row("Compounds",0,"Antimony trioxide","Sb",2,"O",3);
row("Compounds",0,"Antimony pentafluoride","Sb",1,"F",5);
row("Compounds",0,"Antimony pentachloride","Sb",1,"Cl",5);
row("Compounds",0,"Antimony hydride","Sb",1,"H",3);
row("Compounds",0,"Ammonium sulfate","N",2,"H",8,"S",1,"O",4);
row("Compounds",0,"Ammonium nitrate","N",2,"H",4,"O",3);
row("Compounds",0,"Ammonium hydroxide","N",1,"H",5,"O",1);
row("Compounds",0,"Ammonium chloride","N",1,"H",4,"Cl",1);
row("Compounds",0,"Ammonium cerium(IV) nitrate","N",8,"H",8,"Ce",1,"O",18);
row("Compounds",0,"Ammonium bicarbonate","N",1,"H",5,"C",1,"O",3);
row("Compounds",0,"Ammonia","N",1,"H",3);
row("Compounds",0,"Aluminium sulfate","Al",2,"S",3,"O",12);
row("Compounds",0,"Aluminium phosphide","Al",1,"P",1);
row("Compounds",0,"Aluminium oxide","Al",2,"O",3);
row("Compounds",0,"Aluminium nitride","Al",2,"N",1);
row("Compounds",0,"Aluminium nitrate","Al",1,"N",3,"O",9);
row("Compounds",0,"Aluminium hydroxide","Al",1,"O",3,"H",3);
row("Compounds",0,"Aluminium arsenide","Al",1,"As",2);
row("Compounds",0,"Aluminium antimonide","Al",1,"Sb",2);
row("Compounds",8,"Copper(II) chloride","Cu",1,"Cl",2);
row("Compounds",8,"Copper(I) chloride","Cu",1,"Cl",1);
row("Compounds",8,"Cobalt(II) chloride","Co",1,"Cl",2);
row("Compounds",8,"Cobalt(II) bromide","Co",1,"Br",2);
row("Compounds",8,"Chromyl chloride","Cr",1,"O",2,"Cl",2);
row("Compounds",8,"Chromium(III) chloride","Cr",1,"Cl",3);
row("Compounds",8,"Chromium(II) chloride","Cr",1,"Cl",2);
row("Compounds",8,"Cerium(III) chloride","Ce",1,"Cl",3);
row("Compounds",8,"Cerium(III) bromide","Ce",1,"Br",3);
row("Compounds",8,"Calcium fluoride","Ca",1,"F",2);
row("Compounds",8,"Calcium chloride","Ca",1,"Cl",2);
row("Compounds",8,"Zirconium(IV) chloride","Zr",1,"Cl",4);
row("Compounds",8,"Zinc iodide","Zn",1,"I",2);
row("Compounds",8,"Zinc fluoride","Zn",1,"F",2);
row("Compounds",8,"Zinc chloride","Zn",1,"Cl",2);
row("Compounds",8,"Zinc bromide","Zn",1,"Br",2);
row("Compounds",8,"Yttrium(III) fluoride","Y",1,"F",3);
row("Compounds",8,"Yttrium(III) bromide","Y",1,"Br",3);
row("Compounds",8,"Ytterbium(III) chloride","Yb",1,"Cl",3);
row("Compounds",8,"Vanadium(IV) fluoride","V",1,"F",4);
row("Compounds",8,"Vanadium(IV) chloride","V",1,"Cl",4);
row("Compounds",8,"Vanadium(III) fluoride","V",1,"F",3);
row("Compounds",8,"Vanadium(III) chloride","V",1,"Cl",3);
row("Compounds",8,"Vanadium(III) bromide","V",1,"Br",3);
row("Compounds",8,"Vanadium(II) chloride","V",1,"Cl",2);
row("Compounds",8,"Tungsten(VI) Fluoride","W",1,"F",6);
row("Compounds",8,"Tungsten(VI) chloride","W",1,"Cl",6);
row("Compounds",8,"Titanium tetraiodide","Ti",1,"I",4);
row("Compounds",8,"Titanium tetrachloride)","Ti",1,"Cl",4);
row("Compounds",8,"Titanium tetrabromide","Ti",1,"Br",4);
row("Compounds",8,"Titanium(III) chloride","Ti",1,"Cl",3);
row("Compounds",8,"Titanium(II) chloride","Ti",1,"Cl",1);
row("Compounds",8,"Tin(IV) chloride","Sn",1,"Cl",4);
row("Compounds",8,"Tin(II) fluoride","Sn",1,"F",2);
row("Compounds",8,"Tin(II) chloride","Sn",1,"Cl",2);
row("Compounds",8,"Thulium(III) chloride","Tm",1,"Cl",3);
row("Compounds",8,"Thionyl chloride","S",1,"O",1,"Cl",2);
row("Compounds",8,"Sulfuryl chloride","S",1,"O",2,"Cl",2);
row("Compounds",8,"Strontium chloride","Sr",1,"Cl",2);
row("Compounds",8,"Stannous chloride","Sn",1,"Cl",2);
row("Compounds",8,"Sodium iodide","Na",1,"I",1);
row("Compounds",8,"Sodium chloride","Na",1,"Cl",1);
row("Compounds",8,"Sodium bromide","Na",1,"Br",1);
row("Compounds",8,"Sodium astatide","Na",1,"At",1);
row("Compounds",8,"Silver(II) fluoride","Ag",1,"F",2);
row("Compounds",8,"Silver(I) fluoride","Ag",1,"F",1);
row("Compounds",8,"Silver iodide","Ag",1,"I",1);
row("Compounds",8,"Silver chloride","Ag",1,"Cl",1);
row("Compounds",8,"Scandium(III) fluoride","Sc",1,"F",3);
row("Compounds",8,"Scandium(III) chloride","Sc",1,"Cl",3);
row("Compounds",8,"Samarium(III) chloride","Sm",1,"Cl",3);
row("Compounds",8,"Samarium(II) iodide","Sm",1,"I",2);
row("Compounds",8,"Rubidium iodide","Rb",1,"I",1);
row("Compounds",8,"Rubidium fluoride","Rb",1,"F",1);
row("Compounds",8,"Rubidium chloride","Rb",1,"Cl",1);
row("Compounds",8,"Rubidium bromide","Rb",1,"Br",1);
row("Compounds",8,"Rhodium(III) chloride","Rh",1,"Cl",3);
row("Compounds",8,"Radon difluoride","Rn",1,"F",2);
row("Compounds",8,"Radium chloride","Ra",1,"Cl",2);
row("Compounds",8,"Praseodymium(III) chloride","Pr",1,"Cl",3);
row("Compounds",8,"Potassium iodide","K",1,"I",1);
row("Compounds",8,"Potassium Chloride","KCl",1);
row("Compounds",8,"Potassium chloride","K",1,"Cl",1);
row("Compounds",8,"Potassium carbonate","K",2,"C",1,"O",3);
row("Compounds",8,"Potassium bromide","K",1,"Br",1);
row("Compounds",8,"Perchloryl fluoride","Cl",1,"F",1,"O",3);
row("Compounds",8,"Palladium(II) chloride","Pd",1,"Cl",2);
row("Compounds",8,"Oxygen difluoride","O",1,"F",2);
row("Compounds",8,"Nickel(II) chloride","Ni",1,"Cl",2);
row("Compounds",8,"Neodymium(III) chloride","Nd",1,"Cl",3);
row("Compounds",8,"Mercury(II) chloride","Hg",1,"Cl",2);
row("Compounds",8,"Mercury(I) chloride","Hg",2,"Cl",2);
row("Compounds",8,"Manganese(IV) fluoride","Mn",1,"F",4);
row("Compounds",8,"Manganese(III) chloride","Mn",1,"Cl",3);
row("Compounds",8,"Manganese(II) chloride","Mn",1,"Cl",2);
row("Compounds",8,"Magnesium chloride","Mg",1,"Cl",2);
row("Compounds",8,"Magnesium astatide","Mg",1,"At",2);
row("Compounds",8,"Lithium chloride","Li",1,"Cl",1);
row("Compounds",8,"Lithium bromide","Li",1,"Br",1);
row("Compounds",8,"Lead(II) chloride","Pb",1,"Cl",2);
row("Compounds",8,"Iron(III) chloride","Fe",1,"Cl",3);
row("Compounds",8,"Iron(II) chloride","Fe",1,"Cl",2);
row("Compounds",8,"Iridium(IV) chloride","Ir",4,"Cl",1);
row("Compounds",8,"Iodine pentafluoride","I",1,"F",5);
row("Compounds",8,"Iodine monochloride","I",1,"Cl",1);
row("Compounds",8,"Iodine heptafluoride","I",1,"F",7);
row("Compounds",8,"Indium(I) chloride","In",1,"Cl",1);
row("Compounds",8,"Hydrogen fluoride","H",1,"F",1);
row("Compounds",8,"Hydrogen chloride","H",1,"Cl",1);
row("Compounds",8,"Hydrogen bromide","H",1,"Br",1);
row("Compounds",8,"Hafnium tetrachloride","Hf",1,"Cl",4);
row("Compounds",8,"Hafnium fluoride","Hf",1,"F",2);
row("Compounds",8,"Gold(V) fluoride","Au",1,"F",5);
row("Compounds",8,"Gold(III) iodide","Au",1,"I",3);
row("Compounds",8,"Gold(III) fluoride","Au",1,"F",3);
row("Compounds",8,"Gold(III) chloride","Au",2,"Cl",6);
row("Compounds",8,"Gold(III) chloride","Au",1,"Cl",3);
row("Compounds",8,"Gold(III) bromide","Au",2,"Br",6);
row("Compounds",8,"Gold(I) iodide","Au",1,"I",1);
row("Compounds",8,"Gold(I) chloride","Au",1,"Cl",1);
row("Compounds",8,"Gold(I) bromide","Au",1,"Br",1);
row("Compounds",8,"Gold(I III) chloride","Au",4,"Cl",8);
row("Compounds",8,"Germanium(IV) iodide","Ge",1,"I",4);
row("Compounds",8,"Germanium(IV) chloride","Ge",1,"Cl",4);
row("Compounds",8,"Germanium(IV) bromide","Ge",1,"Br",4);
row("Compounds",8,"Germanium(II) iodide","Ge",1,"I",2);
row("Compounds",8,"Germanium(II) chloride","Ge",1,"Cl",2);
row("Compounds",8,"Germanium(II) bromide","Ge",1,"Br",2);
row("Compounds",8,"Europium(III) chloride","Eu",1,"Cl",3);
row("Compounds",8,"Erbium(III) chloride","Er",1,"Cl",3);
row("Compounds",8,"Dysprosium(III) chloride","Dy",1,"Cl",3);
row("Compounds",8,"Cyanuric chloride","C",3,"Cl",3,"N",3);
row("Compounds",8,"Cyanogen chloride","C",1,"N",1,"Cl",1);
row("Compounds",8,"Carbon tetraastatide","C",1,"At",4);
row("Compounds",8,"Caesium fluoride","Cs",1,"F",1);
row("Compounds",8,"Caesium chloride","Cs",1,"Cl",1);
row("Compounds",8,"Cadmium fluoride","Cd",1,"F",2);
row("Compounds",8,"Cadmium chloride","Cd",1,"Cl",2);
row("Compounds",8,"Cadmium bromide","Cd",1,"Br",2);
row("Compounds",8,"Boron trifluoride","B",1,"F",3);
row("Compounds",8,"Boron trichloride","B",1,"Cl",3);
row("Compounds",8,"Beryllium fluoride","Be",1,"F",2);
row("Compounds",8,"Beryllium chloride","Be",1,"Cl",2);
row("Compounds",8,"Beryllium bromide","Be",1,"Br",2);
row("Compounds",8,"Barium chloride","Ba",1,"Cl",2);
row("Compounds",8,"Aluminium fluoride","Al",1,"F",3);
row("Compounds",8,"Aluminium chloride","Al",1,"Cl",3);
row("Compounds",7,"Iodide","I",1);
row("Compounds",7,"Flouride","F",1);
row("Compounds",7,"Chloride","Cl",1);
row("Compounds",7,"Bromide","Br",1);
row("Compounds",7,"Astatide","At",1);
row("Compounds",0,"Ammonium tetrathiocyanatodiamminechromate(III)","N",7,"H",10,"Cr",1,"S",4,"C",4);
