// Weapon systems
global.weapons=19;

// Weapon cooldown settings, Weapon names
global.weapon_rate[  0]=30;    global.weapon_name[  0]="Red Blaster";             global.weapon_sound[0]=sfx_bzzt;
global.weapon_rate[  1]=30;    global.weapon_name[  1]="Blue Photon";             global.weapon_sound[1]=sfx_blaster;
global.weapon_rate[  2]=24;    global.weapon_name[  2]="Green Blaster";           global.weapon_sound[2]=sfx_splut;
global.weapon_rate[  3]=18;    global.weapon_name[  3]="Purple Blaster";          global.weapon_sound[3]=sfx_laser1;
global.weapon_rate[  4]=200;   global.weapon_name[  4]="Seeker Missile";          global.weapon_sound[4]=sfx_missile;
global.weapon_rate[  5]=3;     global.weapon_name[  5]="High ROF Flak Cannon";    global.weapon_sound[5]=sfx_pistol;
global.weapon_rate[  6]=10;    global.weapon_name[  6]="Dual Hypercoil Blaster";  global.weapon_sound[6]=sfx_blaster;
global.weapon_rate[  7]=10;    global.weapon_name[  7]="Spread Projector";        global.weapon_sound[7]=sfx_10mms;
global.weapon_rate[  8]=3;     global.weapon_name[  8]="Smart Bullets";           global.weapon_sound[8]=sfx_10mms;
global.weapon_rate[  9]=16;    global.weapon_name[  9]="Flak Ejector";            global.weapon_sound[9]=sfx_10mms;
global.weapon_rate[ 10]=90;    global.weapon_name[ 10]="Green Ion Cloud";         global.weapon_sound[10]=sfx_hrphotoncannon;
global.weapon_rate[ 11]=4;     global.weapon_name[ 11]="High ROF Flak Minigun";   global.weapon_sound[11]=sfx_dualhypercoilblaster;
global.weapon_rate[ 12]=0;     global.weapon_name[ 12]="Acrid Gas Emitter";       global.weapon_sound[12]=sfx_muffled_ordinance;
global.weapon_rate[ 13]=50;    global.weapon_name[ 13]="Blastomatic 5000";        global.weapon_sound[13]=sfx_bunkmpf;
global.weapon_rate[ 14]=20;    global.weapon_name[ 14]="Lightning Gun";           global.weapon_sound[14]=sfx_lectro;
global.weapon_rate[ 15]=15;    global.weapon_name[ 15]="360 Flak Ejector";        global.weapon_sound[15]=sfx_10mms;
global.weapon_rate[ 16]=40;    global.weapon_name[ 16]="Blade Gun";               global.weapon_sound[16]=sfx_schwang;
global.weapon_rate[ 17]=34;    global.weapon_name[ 17]="Quantum Torpedo";         global.weapon_sound[17]=sfx_ptorp;
global.weapon_rate[ 18]=60;    global.weapon_name[ 18]="Photon Mine";             global.weapon_sound[18]=sfx_splut;
global.weapon_rate[ 19]=0;     global.weapon_name[ 19]="";
global.weapon_rate[ 20]=0;     global.weapon_name[ 20]="";
global.weapon_rate[ 21]=0;     global.weapon_name[ 21]="";
global.weapon_rate[ 22]=0;     global.weapon_name[ 22]="";
global.weapon_rate[ 23]=0;     global.weapon_name[ 23]="";
global.weapon_rate[ 24]=0;     global.weapon_name[ 24]="";
global.weapon_rate[ 25]=0;     global.weapon_name[ 25]="";
global.weapon_rate[ 25]=0;     global.weapon_name[ 25]="";
global.weapon_rate[ 26]=0;     global.weapon_name[ 26]="";
global.weapon_rate[ 27]=0;     global.weapon_name[ 27]="";
global.weapon_rate[ 28]=0;     global.weapon_name[ 28]="";
global.weapon_rate[ 29]=0;     global.weapon_name[ 29]="";
global.weapon_rate[ 30]=0;     global.weapon_name[ 30]="";
global.weapon_rate[ 31]=0;     global.weapon_name[ 31]="";
global.weapon_rate[ 32]=0;     global.weapon_name[ 32]="";
global.weapon_rate[ 33]=0;     global.weapon_name[ 33]="";
global.weapon_rate[ 34]=0;     global.weapon_name[ 34]="";
global.weapon_rate[ 35]=0;     global.weapon_name[ 35]="";
global.weapon_rate[ 36]=0;     global.weapon_name[ 36]="";
global.weapon_rate[ 37]=0;     global.weapon_name[ 37]="";
global.weapon_rate[ 38]=0;     global.weapon_name[ 38]="";
global.weapon_rate[ 39]=0;     global.weapon_name[ 39]="";
global.weapon_rate[ 40]=0;     global.weapon_name[ 40]="";
global.weapon_rate[ 41]=0;     global.weapon_name[ 41]="";
global.weapon_rate[ 42]=0;     global.weapon_name[ 42]="";
global.weapon_rate[ 43]=0;     global.weapon_name[ 43]="";
global.weapon_rate[ 44]=0;     global.weapon_name[ 44]="";
global.weapon_rate[ 45]=0;     global.weapon_name[ 45]="";
global.weapon_rate[ 46]=0;     global.weapon_name[ 46]="";
global.weapon_rate[ 47]=0;     global.weapon_name[ 47]="";
global.weapon_rate[ 48]=0;     global.weapon_name[ 48]="";
global.weapon_rate[ 49]=0;     global.weapon_name[ 49]="";
global.weapon_rate[ 50]=0;     global.weapon_name[ 50]="";
global.weapon_rate[ 51]=0;     global.weapon_name[ 51]="";
global.weapon_rate[ 52]=0;     global.weapon_name[ 52]="";
global.weapon_rate[ 53]=0;     global.weapon_name[ 53]="";
global.weapon_rate[ 54]=0;     global.weapon_name[ 54]="";
global.weapon_rate[ 55]=0;     global.weapon_name[ 55]="";
global.weapon_rate[ 56]=0;     global.weapon_name[ 56]="";
global.weapon_rate[ 57]=0;     global.weapon_name[ 57]="";
global.weapon_rate[ 58]=0;     global.weapon_name[ 58]="";
global.weapon_rate[ 59]=0;     global.weapon_name[ 59]="";
global.weapon_rate[ 60]=0;     global.weapon_name[ 60]="";
global.weapon_rate[ 61]=0;     global.weapon_name[ 61]="";
global.weapon_rate[ 62]=0;     global.weapon_name[ 62]="";
global.weapon_rate[ 63]=0;     global.weapon_name[ 63]="";
global.weapon_rate[ 64]=0;     global.weapon_name[ 64]="";
global.weapon_rate[ 65]=0;     global.weapon_name[ 65]="";
global.weapon_rate[ 66]=0;     global.weapon_name[ 66]="";
global.weapon_rate[ 67]=0;     global.weapon_name[ 67]="";
global.weapon_rate[ 68]=0;     global.weapon_name[ 68]="";
global.weapon_rate[ 69]=0;     global.weapon_name[ 69]="";
global.weapon_rate[ 70]=0;     global.weapon_name[ 70]="";
global.weapon_rate[ 71]=0;     global.weapon_name[ 71]="";
global.weapon_rate[ 72]=0;     global.weapon_name[ 72]="";
global.weapon_rate[ 73]=0;     global.weapon_name[ 73]="";
global.weapon_rate[ 74]=0;     global.weapon_name[ 74]="";
global.weapon_rate[ 75]=0;     global.weapon_name[ 75]="";
global.weapon_rate[ 76]=0;     global.weapon_name[ 76]="";
global.weapon_rate[ 77]=0;     global.weapon_name[ 77]="";
global.weapon_rate[ 78]=0;     global.weapon_name[ 78]="";
global.weapon_rate[ 79]=0;     global.weapon_name[ 79]="";
global.weapon_rate[ 80]=0;     global.weapon_name[ 80]="";
global.weapon_rate[ 81]=0;     global.weapon_name[ 81]="";
global.weapon_rate[ 82]=0;     global.weapon_name[ 82]="";
global.weapon_rate[ 83]=0;     global.weapon_name[ 83]="";
global.weapon_rate[ 84]=0;     global.weapon_name[ 84]="";
global.weapon_rate[ 85]=0;     global.weapon_name[ 85]="";
global.weapon_rate[ 86]=0;     global.weapon_name[ 86]="";
global.weapon_rate[ 87]=0;     global.weapon_name[ 87]="";
global.weapon_rate[ 88]=0;     global.weapon_name[ 88]="";
global.weapon_rate[ 89]=0;     global.weapon_name[ 89]="";
global.weapon_rate[ 90]=0;     global.weapon_name[ 90]="";
global.weapon_rate[ 91]=0;     global.weapon_name[ 91]="";
global.weapon_rate[ 92]=0;     global.weapon_name[ 92]="";
global.weapon_rate[ 93]=0;     global.weapon_name[ 93]="";
global.weapon_rate[ 94]=0;     global.weapon_name[ 94]="";
global.weapon_rate[ 95]=0;     global.weapon_name[ 95]="";
global.weapon_rate[ 96]=0;     global.weapon_name[ 96]="";
global.weapon_rate[ 97]=0;     global.weapon_name[ 97]="";
global.weapon_rate[ 98]=0;     global.weapon_name[ 98]="";
global.weapon_rate[ 99]=0;     global.weapon_name[ 99]="";
global.weapon_rate[100]=0;     global.weapon_name[100]="";
global.weapon_rate[101]=0;     global.weapon_name[101]="";
global.weapon_rate[102]=0;     global.weapon_name[102]="";
global.weapon_rate[103]=0;     global.weapon_name[103]="";
global.weapon_rate[104]=0;     global.weapon_name[104]="";
global.weapon_rate[105]=0;     global.weapon_name[105]="";
global.weapon_rate[106]=0;     global.weapon_name[106]="";
global.weapon_rate[107]=0;     global.weapon_name[107]="";
global.weapon_rate[108]=0;     global.weapon_name[108]="";
global.weapon_rate[109]=0;     global.weapon_name[109]="";
global.weapon_rate[110]=0;     global.weapon_name[110]="";
global.weapon_rate[111]=0;     global.weapon_name[111]="";
global.weapon_rate[112]=0;     global.weapon_name[112]="";
global.weapon_rate[113]=0;     global.weapon_name[113]="";
global.weapon_rate[114]=0;     global.weapon_name[114]="";
global.weapon_rate[115]=0;     global.weapon_name[115]="";
global.weapon_rate[116]=0;     global.weapon_name[116]="";
global.weapon_rate[117]=0;     global.weapon_name[117]="";
global.weapon_rate[118]=0;     global.weapon_name[118]="";
global.weapon_rate[119]=0;     global.weapon_name[119]="";
global.weapon_rate[120]=0;     global.weapon_name[120]="";
global.weapon_rate[121]=0;     global.weapon_name[121]="";
global.weapon_rate[122]=0;     global.weapon_name[122]="";
global.weapon_rate[123]=0;     global.weapon_name[123]="";
global.weapon_rate[124]=0;     global.weapon_name[124]="";
global.weapon_rate[125]=0;     global.weapon_name[125]="";
global.weapon_rate[126]=0;     global.weapon_name[126]="";
global.weapon_rate[127]=0;     global.weapon_name[127]="";
global.weapon_rate[128]=0;     global.weapon_name[128]="";
global.weapon_rate[129]=0;     global.weapon_name[129]="";
global.weapon_rate[130]=0;     global.weapon_name[130]="";
global.weapon_rate[131]=0;     global.weapon_name[131]="";
global.weapon_rate[132]=0;     global.weapon_name[132]="";
global.weapon_rate[133]=0;     global.weapon_name[133]="";
global.weapon_rate[134]=0;     global.weapon_name[134]="";
global.weapon_rate[135]=0;     global.weapon_name[135]="";
global.weapon_rate[136]=0;     global.weapon_name[136]="";
global.weapon_rate[137]=0;     global.weapon_name[137]="";
global.weapon_rate[138]=0;     global.weapon_name[138]="";
global.weapon_rate[139]=0;     global.weapon_name[139]="";
global.weapon_rate[140]=0;     global.weapon_name[140]="";
global.weapon_rate[141]=0;     global.weapon_name[141]="";
global.weapon_rate[142]=0;     global.weapon_name[142]="";


