var o;
o=argument0;
if ( o == o_ai_asterbase1 ) return true;
if ( o == o_ai_asterbase2 ) return true;
if ( o == o_ai_asterbase3 ) return true;
if ( o == o_ai_asterbase4 ) return true;
if ( o == o_ai_asterbase5 ) return true;
if ( o == o_ai_asterbase6 ) return true;
if ( o == o_ai_asterbase7 ) return true;
if ( o == o_ai_asterbase8 ) return true;
if ( o == o_ai_asterbase9 ) return true;
if ( o == o_ai_asterbase10 ) return true;
if ( o == o_ai_gunplatform ) return true;
if ( o == o_ai_ufse_starbase ) return true;
return false;
