var i;
i=argument0; // object_index
if ( i == o_ai_durak_spaceliner ) return true;
if ( i == o_ai_durak_freighter ) return true;
if ( i == o_ai_durak_destroyer ) return true;
if ( i == o_ai_durak_bomber ) return true;
if ( i == o_ai_durak_infiltrator ) return true;
if ( i == o_ai_durak_multipurpose ) return true;
if ( i == o_ai_durak_cruiser ) return true;
if ( i == o_ai_allindorna_cruiser ) return true;
if ( i == o_ai_menaling_tug ) return true;
if ( i == o_ai_kratek_cruiser ) return true;
if ( i == o_ai_chronodila_cruiser ) return true;
if ( i == o_ai_phenokti_cruiser ) return true;
if ( i == o_ai_military_skiff ) return true;
if ( i == o_ai_starliner ) return true;
if ( i == o_ai_starliner_lifeboat ) return true;
if ( i == o_ai_starliner_rearpod ) return true;
if ( i == o_ai_pilexu_individual ) return true;
if ( i == o_ai_pilexu_grouped ) return true;
if ( i == o_ai_pilexu_mass ) return true;
if ( i == o_ai_alvaki_exocraft ) return true;
if ( i == o_ai_thilon_prong ) return true;
if ( i == o_ai_remnant_cruiser ) return true;
if ( i == o_ai_ursae_organaut ) return true;
if ( i == o_ai_valspectre_cruiser ) return true;
if ( i == o_ai_claw_cruiser ) return true;
if ( i == o_ai_claw_destroyer ) return true;
if ( i == o_ai_claw_intercepter ) return true;
if ( i == o_ai_claw_cruiser2 ) return true;
if ( i == o_ai_kiriahal ) return true;
if ( i == o_ai_pirate1 ) return true;
if ( i == o_ai_pirate2 ) return true;
if ( i == o_ai_pirate3 ) return true;
if ( i == o_ai_pirate4 ) return true;
if ( i == o_ai_drifter ) return true;
return false;
