shader_set(gles_LayerCombiner);
texture_set_stage(global.gles_LayerCombiner_tweens,global.gles_LayerCombiner_textures[0]);
texture_set_stage(global.gles_LayerCombiner_tex0,global.gles_LayerCombiner_textures[1]);
texture_set_stage(global.gles_LayerCombiner_tex1,global.gles_LayerCombiner_textures[2]);
texture_set_stage(global.gles_LayerCombiner_tex2,global.gles_LayerCombiner_textures[3]);
shader_set_uniform_f(global.gles_LayerCombiner_time,argument0);
shader_set_uniform_f(global.gles_LayerCombiner_ts1,global.gles_LayerCombiner_ts[0]);
shader_set_uniform_f(global.gles_LayerCombiner_ts2,global.gles_LayerCombiner_ts[1]);
shader_set_uniform_f(global.gles_LayerCombiner_ts3,global.gles_LayerCombiner_ts[2]);
shader_set_uniform_f(global.gles_LayerCombiner_t1,global.gles_LayerCombiner_t[0]);
shader_set_uniform_f(global.gles_LayerCombiner_t2,global.gles_LayerCombiner_t[1]);
shader_set_uniform_f(global.gles_LayerCombiner_t3,global.gles_LayerCombiner_t[2]);
shader_set_uniform_f(global.gles_LayerCombiner_a1,global.gles_LayerCombiner_a[0]);
shader_set_uniform_f(global.gles_LayerCombiner_a2,global.gles_LayerCombiner_a[1]);
shader_set_uniform_f(global.gles_LayerCombiner_a3,global.gles_LayerCombiner_a[2]);
shader_set_uniform_f(global.gles_LayerCombiner_b1,global.gles_LayerCombiner_b[0]);
shader_set_uniform_f(global.gles_LayerCombiner_b2,global.gles_LayerCombiner_b[1]);
shader_set_uniform_f(global.gles_LayerCombiner_b3,global.gles_LayerCombiner_b[2]);
shader_set_uniform_f(global.gles_LayerCombiner_w1,global.gles_LayerCombiner_w[0]);
shader_set_uniform_f(global.gles_LayerCombiner_w2,global.gles_LayerCombiner_w[1]);
shader_set_uniform_f(global.gles_LayerCombiner_w3,global.gles_LayerCombiner_w[2]);
shader_set_uniform_f(global.gles_LayerCombiner_c1,
 global.gles_LayerCombiner_co1[0],
 global.gles_LayerCombiner_co1[1],
 global.gles_LayerCombiner_co1[2]
);
shader_set_uniform_f(global.gles_LayerCombiner_c2,
 global.gles_LayerCombiner_co2[0],
 global.gles_LayerCombiner_co2[1],
 global.gles_LayerCombiner_co2[2]
);
shader_set_uniform_f(global.gles_LayerCombiner_c3,
 global.gles_LayerCombiner_co3[0],
 global.gles_LayerCombiner_co3[1],
 global.gles_LayerCombiner_co3[2]
);
